---Liste ordonnée des types de prototypes testés pour chaque mod. Pour chaque type, `data-final-fixes`
---cherche les clés `<type>`, `<type>-name` et `<type>-description` dans la table de traduction du mod.
---@type string[]
return {
    "achievement",
    "airborne-pollutant",
    "ammo-category",
    "autoplace-control",
    "controls",
    "damage-type",
    "decorative",
    "entity",
    "equipment",
    "equipment-category",
    "fluid",
    "fuel-category",
    "item",
    "item-group",
    "module-category",
    "noise-expression",
    "noise-layer",
    "optimized-particle",
    "recipe",
    "recipe-category",
    "resource-category",
    "shortcut",
    "space-location",
    "subgroup",
    "technology",
    "tile",
    "tips-and-tricks-item",
    "trivial-smoke",
    "tutorial",
    "utility-constants",
    "utility-sounds",
    "utility-sprites",
    "virtual-signal"
}