return {
    ---------------
    --aai-industry.cfg
    ["item-name"] = {
        ["stone-tablet"]="Tablette de pierre",
        ["motor"]="Moteur monocylindre",
        ["electric-motor"]="Petit moteur électrique",
        ["engine-unit"]="Moteur multicylindre",
        ["electric-engine-unit"]="Grand moteur électrique",
        ["burner-lab"]="Laboratoire thermique",
        ["lab"]="Laboratoire électrique",
        ["burner-assembling-machine"]="Machine d'assemblage thermique",
        ["burner-turbine"]="Turbogénérateur thermique",
        ["small-electric-pole"]="Petit poteau électrique en bois",
        ["small-iron-electric-pole"]="Petit poteau électrique en fer",
        ["processed-fuel"]="Combustible transformé",
        ["wooden-chest"]="Coffre en bois",
        ["sand"]="Sable",
        ["solid-sand"]="Sable lavé",
        ["washed-sand"]="Sable lavé",
        ["glass"]="Verre",
        ["area-mining-drill"]="Grande foreuse minière",
    },
    ["item-description"] = {
        ["burner-turbine"]="Production d'électricité autonome, simple mais inefficace.",
        ["processed-fuel"]="Un carburant efficace conçu pour alimenter les véhicules, mais qui peut être utilisé à d'autres fins.",
        ["area-mining-drill"]="Une foreuse minière électrique plus grande avec une portée et une vitesse accrue et des emplacements de module supplémentaires.",
    },
    ["recipe-name"] = {
        ["oil-processing-heavy"]="Traitement du pétrole brut",
        ["sand-from-stone"]="Sable",
        ["glass-from-sand"]="Verre",
    },
    ["entity-name"] = {
        ["burner-lab"]="Laboratoire thermique",
        ["lab"]="Laboratoire électrique",
        ["burner-assembling-machine"]="Machine d'assemblage thermique",
        ["burner-turbine"]="Turbogénérateur thermique",
        ["burner-turbine-water"]="Turbogénérateur thermique",
        ["burner-turbine-generator"]="Turbogénérateur thermique",
        ["powered-offshore-pump"]="Pompe côtière",
        ["offshore-pump-output"]="Pompe côtière ",
        ["small-electric-pole"]="Petit poteau électrique en bois",
        ["small-iron-electric-pole"]="Petit poteau électrique en fer",
        ["fuel-processor"]="Transformateur de combustible",
        ["stone-wall"]="Mur en pierre",
        ["concrete-block-wall"]="Mur en blocs de béton",
        ["concrete-wall"]="Mur en béton",
        ["refined-concrete-wall"]="Mur en béton armé",
        ["steel-wall"]="Mur en acier",
        ["industrial-furnace"]="Four industriel",
        ["area-mining-drill"]="Grande foreuse minière",
    },
    ["entity-description"] = {
        ["burner-turbine"]="Production d'électricité autonome, simple mais inefficace.",
        ["steel-wall"]="Mur avec une très grande résistance aux dégâts. Les pointes infligent également un peu de dégâts à l'attaquant.",
        ["area-mining-drill"]="Une foreuse minière électrique plus grande avec une portée et une vitesse accrue et des emplacements de module supplémentaires.",
    },
    ["fuel-category-name"] = {
        ["chemical"]="Carburant",
        ["processed-chemical"]="Produits chimiques transformés",
    },
    ["tile-name"] = {
        ["stone-path"]="Chemin de brique",
        ["rough-stone-path"]="Chemin de pierre",
    },
    ["technology-name"] = {
        ["basic-logistics"]="Logistique de base",
        ["basic-logistics-1"]="Logistique de base 1",
        ["basic-logistics-2"]="Logistique de base 2",
        ["logistics-0"]="Logistique de base 2",
        ["burner-mechanics"]="Mécanique thermique",
        ["electricity"]="Électricité",
        ["electric-lab"]="Laboratoire électrique",
        ["basic-fluid-handling"]="Traitement basique des fluides",
        ["steam-power"]="Puissance vapeur",
        ["concrete-walls"]="Murs en béton",
        ["steel-walls"]="Mur en acier",
        ["engine"]="Moteur multicylindre",
        ["electric-engine"]="Grand moteur électrique",
        ["automobilism"]="Automobile",
        ["fuel-processing"]="Traitement des combustibles",
        ["sand-processing"]="Traitement du sable",
        ["glass-processing"]="Traitement du verre",
        ["industrial-furnace"]="Four industriel",
        ["area-mining-drill"]="Grande foreuse minière",
        ["medium-electric-pole"]="Poteau électrique moyen",
    },
    ["technology-description"] = {
        ["basic-logistics"]="Les bases du déplacement des objets.",
        ["basic-logistics-1"]="Moyens de transport plus rapides et plus flexibles.",
        ["basic-logistics-2"]="Moyens de transport plus rapides et plus flexibles.",
        ["burner-mechanics"]="Des moteurs simples qui permettent d'alimenter de nombreux appareils.",
        ["electricity"]="La base : Turbogénérateur thermique, moteurs électriques et petits poteaux électriques.",
        ["electronics"]="Composants électroniques pour le traitement basique du signal.",
        ["electric-lab"]="La recherche alimentée par l'électricité",
        ["basic-fluid-handling"]="Les bases de la tuyauterie.",
        ["steam-power"]="Puissance plus efficace issue de la vapeur.",
        ["concrete-walls"]="Des murs plus solides en béton.",
        ["steel-walls"]="Mur avec une très grande résistance aux dégâts. Les pointes infligent également un peu de dégâts à l'attaquant.",
        ["engine"]="Moteurs efficaces et de grande puissance pour les véhicules et la robotique.",
        ["electric-engine"]="Grands moteurs polyphasés sans balais.",
        ["automobilism"]="Véhicule à moteur utilisé pour le transport.",
        ["sand-processing"]="Broyage, meulage et filtration de la matière première dans du sable propre.",
        ["glass-processing"]="Fusion du sable en verre.",
        ["area-mining-drill"]="Une foreuse minière électrique plus grande avec une portée et une vitesse accrue et des emplacements de module supplémentaires.",
        ["medium-electric-pole"]="Des moyens plus flexibles de distribuer l'électricité.",
    }
    -------------------------
}
