return {
    ---------------
    --aai-programmable-vehicles.cfg
    ["controls"] = {
        ["create-toggle-controller"]="Créer un contrôleur à distance ou basculer entre le mode Chemin et Unités.",
        ["save-unit-group-1"]="Sauvegarder le groupe d'unités 1",
        ["save-unit-group-2"]="Sauvegarder le groupe d'unités 2",
        ["save-unit-group-3"]="Sauvegarder le groupe d'unités 3",
        ["save-unit-group-4"]="Sauvegarder le groupe d'unités 4",
        ["save-unit-group-5"]="Sauvegarder le groupe d'unités 5",
        ["save-unit-group-6"]="Sauvegarder le groupe d'unités 6",
        ["save-unit-group-7"]="Sauvegarder le groupe d'unités 7",
        ["save-unit-group-8"]="Sauvegarder le groupe d'unités 8",
        ["save-unit-group-9"]="Sauvegarder le groupe d'unités 9",
        ["save-unit-group-0"]="Sauvegarder le groupe d'unités 0",
        ["load-unit-group-1"]="Charger le groupe d'unités 1",
        ["load-unit-group-2"]="Charger le groupe d'unités 2",
        ["load-unit-group-3"]="Charger le groupe d'unités 3",
        ["load-unit-group-4"]="Charger le groupe d'unités 4",
        ["load-unit-group-5"]="Charger le groupe d'unités 5",
        ["load-unit-group-6"]="Charger le groupe d'unités 6",
        ["load-unit-group-7"]="Charger le groupe d'unités 7",
        ["load-unit-group-8"]="Charger le groupe d'unités 8",
        ["load-unit-group-9"]="Charger le groupe d'unités 9",
        ["load-unit-group-0"]="Charger le groupe d'unités 0",
    },
    ["entity-name"] = {
        ["vehicle-depot"]="Dépôt de véhicules",
        ["vehicle-depot-chest"]="Conteneur de dépôt de véhicules",
        ["vehicle-depot-combinator"]="Échange de données des dépôts de véhicules",
        ["vehicle-deployer"]="Déployeur de véhicules",
        ["vehicle-deployer-overlay"]="Déployeur de véhicules",
        ["vehicle-deployer-belt"]="Déployeur de véhicules",
        ["vehicle-deployer-reserved"]="Espace réservé au déployeur de véhicules",
        ["vehicle-deployer-combinator"]="Données sur les unités déployées par les déployeur de véhicules",
        ["remote-unit-data"]="Modification des données de l'unité",
        ["unit-scan"]="Scanneur d'unités",
        ["position-beacon"]="Balise de position",
    },
    ["entity-description"] = {
        ["vehicle-depot-combinator"]="Réglez les signaux ici ou connectez-vous à un réseau pour régler les paramètres d'échange du dépôt.",
        ["vehicle-deployer-combinator"]="Réglez les signaux ici ou connectez-vous à un réseau pour régler les données de l'unité déployée.",
        ["position-beacon"]="Une balise statique (combinateur) qui affiche son identifiant et sa position. Peut être utilisé comme un point de passage à l'aide du contrôleur de chemin.",
    },
    ["recipe-name"] = {
        ["vehicle-deployer"]="Déployeur de véhicules",
        ["vehicle-depot"]="Dépôt de véhicules",
        ["unit-remote-control"]="Contrôleur à distance d'unités",
        ["cannon-shell-precision"]="Obus de canon de précision",
        ["explosive-cannon-shell-precision"]="Obus de canon explosif de précision",
    },
    ["item-name"] = {
        ["vehicle-deployer"]="Déployeur de véhicules",
        ["vehicle-depot"]="Dépôt de véhicules",
        ["vehicle-depot-chest"]="Conteneur de dépôt de véhicules",
        ["vehicle-depot-combinator"]="Échange de données des dépôts de véhicules",
        ["unit-remote-control"]="Contrôleur d'unités à distance",
        ["path-remote-control"]="Contrôleur de chemin à distance ",
        ["cannon-shell-precision"]="Obus de canon de précision",
        ["explosive-cannon-shell-precision"]="Obus de canon explosif de précision",
        ["unit-scan"]="Scanneur d'unités",
        ["position-beacon"]="Balise de position",
        ["tank-cannon"]="Canon",
        ["tank-cannon-2"]="Canon",
        ["tank-cannon-3"]="Canon",
        ["tank-machine-gun"]="Mitrailleuse Gatling",
        ["tank-gatling-gun"]="Mitrailleuse Gatling",
        ["tank-laser"]="Laser",
        ["tank-artiller-1"]="Artillerie",
        ["tank-artiller-2"]="Artillerie",
        ["tank-flamethrower"]="Lance-flammes",
        ["tank-flamethrower-2"]="Lance-flammes",
        ["tank-flamethrower-3"]="Lance-flammes",
    },
    ["item-description"] = {
        ["path-remote-control"]="Crée et édite des chemins avec des points de passage pour les véhicules.",
        ["explosive-cannon-shell-precision"]="Comme l'obus de canon explosif, mais vise une seule cible au lieu d'une ligne pour réduire les dommages collatéraux.",
        ["position-beacon"]="Une balise statique (combinateur) qui affiche son identifiant et sa position. Peut être utilisé comme un point de passage à l'aide du contrôleur de chemin.",
    },
    ["virtual-signal-name"] = {
        ["chip"]="puce",
        ["active-state-on"]="Activée",
        ["active-state-off"]="Désactivée",
        ["active-state-auto"]="Automatique",
        ["signal-position-beacon-id"]="Identifiant de la balise de position",
        ["signal-vehicle-depot-id"]="Identifiant du dépôt de véhicules",
    },
    ["technology-name"] = {
        ["engine"]="Moteur haute performance",
        ["automobilism"]="Automobile",
        ["vehicle-deployment"]="Déploiement automatisé des véhicules",
        ["vehicle-depot"]="Dépôt de véhicules",
        ["programmable-vehicle-structures"]="Structures de véhicules programmables",
        ["position-beacon"]="Balise de position",
    },
    ["technology-description"] = {
        ["engine"]="Moteurs à haut rapport puissance/poids pour les véhicules et la robotique.",
        ["automobilism"]="Véhicule à moteur utilisé pour le transport.",
        ["tanks"]="Un puissant véhicule offensif avec une armure lourde et un canon.",
        ["programmable-structures"]="Analyse les tuiles pour détecter les ressources, les ennemis et les structures. Placer les zones automatiquement aux coordonnées. Analyse la position des tuiled de zone.",
        ["position-beacon"]="Une balise statique (combinateur) qui affiche son identifiant et sa position. Peut être utilisé comme un point de passage à l'aide du contrôleur de chemin.",
    }
    -------------------------
}
