return {
    ---------------
    --AdvancedBeltsSA.cfg
    ["item-name"] = {
        ["extreme-belt"]="Convoyeur avancé",
        ["extreme-splitter"]="Répartiteur avancé",
        ["extreme-underground"]="Convoyeur souterrain avancé",
        ["extreme-loader"]="Chargeur avancé",
        ["aai-extreme-loader"]="Chargeur avancé",
        ["extreme-belt-loader"]="Chargeur avancé",
        ["extreme-belt-beltbox"]="Boîte de convoyeur avancé",
        ["ultimate-belt"]="Convoyeur élite",
        ["ultimate-splitter"]="Répartiteur élite",
        ["ultimate-underground"]="Convoyeur souterrain élite",
        ["ultimate-loader"]="Chargeur élite",
        ["aai-ultimate-loader"]="Chargeur élite",
        ["ultimate-belt-loader"]="Chargeur élite",
        ["ultimate-belt-beltbox"]="Boîte de convoyeur élite",
        ["high-speed-belt"]="Hyper-convoyeur",
        ["high-speed-splitter"]="Hyper-répartiteur",
        ["high-speed-underground"]="Hyper-convoyeur souterrain",
        ["high-speed-loader"]="Hyper-chargeur",
        ["aai-high-speed-loader"]="Hyper-chargeur",
        ["high-speed-belt-loader"]="Hyper-chargeur",
        ["high-speed-belt-beltbox"]="Hyper-boîte de convoyeur",
    },
    ["recipe-name"] = {
        ["aai-high-speed-loader"]="Hyper-chargeur",
        ["high-speed-belt-loader"]="Hyper-chargeur",
        ["high-speed-belt-beltbox"]="Hyper-boîte de convoyeur",
    },
    ["entity-name"] = {
        ["extreme-belt"]="Convoyeur avancé",
        ["extreme-splitter"]="Répartiteur avancé",
        ["extreme-underground"]="Convoyeur souterrain avancé",
        ["extreme-loader"]="Chargeur avancé",
        ["aai-extreme-loader"]="Chargeur avancé",
        ["extreme-belt-loader"]="Chargeur avancé",
        ["extreme-belt-beltbox"]="Boîte de convoyeur avancé",
        ["ultimate-belt"]="Convoyeur élite",
        ["ultimate-splitter"]="Répartiteur élite",
        ["ultimate-underground"]="Convoyeur souterrain élite",
        ["ultimate-loader"]="Chargeur élite",
        ["aai-ultimate-loader"]="Chargeur élite",
        ["ultimate-belt-loader"]="Chargeur élite",
        ["ultimate-belt-beltbox"]="Boîte de convoyeur élite",
        ["high-speed-belt"]="Hyper-convoyeur",
        ["high-speed-splitter"]="Hyper-répartiteur",
        ["high-speed-underground"]="Hyper-convoyeur souterrain",
        ["high-speed-loader"]="Hyper-chargeur",
        ["aai-high-speed-loader"]="Hyper-chargeur",
        ["high-speed-belt-loader"]="Hyper-chargeur",
        ["high-speed-belt-beltbox"]="Hyper-boîte de convoyeur",
    },
    ["item-description"] = {
        ["extreme-splitter"]="Sépare et/ou réunit les convoyeurs 1:1.",
        ["ultimate-splitter"]="Sépare et/ou réunit les convoyeurs 1:1.",
        ["high-speed-splitter"]="Sépare et/ou réunit les convoyeurs 1:1.",
    },
    ["entity-description"] = {
        ["extreme-splitter"]="Sépare et/ou réunit les convoyeurs 1:1.",
        ["ultimate-splitter"]="Sépare et/ou réunit les convoyeurs 1:1.",
        ["high-speed-splitter"]="Sépare et/ou réunit les convoyeurs 1:1.",
    },
    ["technology-name"] = {
        ["extreme-logistics"]="Logistique 5",
        ["ultimate-logistics"]="Logistique 6",
        ["high-speed-logistics"]="Logistique 7",
        ["aai-extreme-loader"]="Chargeur avancé",
        ["aai-ultimate-loader"]="Chargeur élite",
        ["aai-high-speed-loader"]="Hyper-chargeur",
    },
    ["technology-description"] = {
        ["extreme-logistics"]="Des moyens de transport plus rapides et plus flexibles.",
        ["ultimate-logistics"]="Si ce n'est pas assez rapide, il y a encore un autre niveau !",
        ["high-speed-logistics"]="Les choses vont si vite qu'on a l'impression qu'elles reculent.",
    }
    -------------------------
}
