return {
    ---------------
    --Armored-train.cfg
    ["entity-name"] = {
        ["armored-locomotive-mk1"]="Locomotive blindée",
        ["minigun-turret-mk1"]="Tourelle mitrailleuse Vulcan",
        ["minigun-platform-mk1"]="Plateforme avec tourelle mitrailleuse Vulcan",
        ["minigun-platform-mk2"]="Plateforme avec double tourelle mitrailleuse Vulcan",
        ["shotgun-turret-mk1"]="Canon Storm",
        ["shotgun-platform-mk1"]="Plateforme avec canon Strom",
        ["shotgun-platform-mk2"]="Plateforme avec double canon Strom",
        ["cannon-turret-mk1"]="Tourelle d'artillerie Rainmetal",
        ["cannon-platform-mk1"]="Plateforme avec tourelle d'artillerie Rainmetal",
        ["cannon-turret-mk2"]="Tourelle d'artillerie Cyclops",
        ["cannon-platform-mk2"]="Plateforme avec tourelle d'artillerie Cyclops",
        ["rocket-turret-mk1"]="Tourelle lance-missiles Hurricane ",
        ["rocket-platform-mk1"]="Plateforme avec tourelle lance-missiles Hurricane",
        ["rocket-turret-mk2"]="Tourelle lance-missiles Swingfire ",
        ["rocket-platform-mk2"]="Plateforme avec tourelle lance-missiles Swingfire",
        ["flamethrower-turret-mk1"]="Tourelle lance-flammes Incinerator",
        ["flamethrower-platform-mk1"]="Plateforme avec tourelle lance-flammes Incinerator",
        ["flamethrower-platform-mk2"]="Plateforme avec double tourelle lance-flammes Incinerator",
        ["radar-mk1"]="Radar",
        ["radar-platform-mk1"]="Plateforme avec radar",
        ["searchlight-turret-mk1"]="Lampe de recherche",
        ["searchlight-platform-mk1"]="Plateforme avec lampe de recherche",
        ["repair-arm-mk1"]="Bras de réparation",
        ["repair-platform-mk1"]="Plateforme avec bras de réparation",
    },
    ["entity-description"] = {
        ["armored-locomotive-mk1"]="Plus lent et plus lourd mais idéal pour broyer les ennemis les plus coriaces",
        ["minigun-platform-mk1"]="Cadence de tir rapide. Proche et moyenne portée",
        ["minigun-platform-mk2"]="Cadence de tir rapide. Proche et moyenne portée",
        ["shotgun-platform-mk1"]="Cadence de tir moyenne. À courte portée seulement. Dispersion des balles",
        ["cannon-platform-mk1"]="Cadence de tir moyenne. Proche et moyenne portée. Les munitions explosives ne sont pas recommandées",
        ["cannon-platform-mk2"]="Cadence de tir lente. Longue portée. Les munitions explosives sont recommandées pour les bâtiments dotés d'un filtre de cible.",
        ["rocket-platform-mk1"]="Cadence de tir rapide. Proche et moyenne portée. Les munitions explosives ne sont pas recommandées",
        ["rocket-platform-mk2"]="Cadence de tir lente. Longue portée. Les munitions explosives sont recommandées pour les bâtiments dotés d'un filtre de cible.",
        ["flamethrower-platform-mk1"]="Cadence de tir moyenne. Portée rapprochée uniquement. Dégâts de type feu",
        ["flamethrower-platform-mk2"]="Cadence de tir moyenne. Portée rapprochée uniquement. Dégâts de type feu",
        ["radar-platform-mk1"]="Révèle le secteur de la carte actuelle du train",
        ["searchlight-platform-mk1"]="À courte distance seulement. Source de lumière. S'active lorsque des ennemis sont à proximité",
        ["repair-platform-mk1"]="Utilise des packs de réparation pour réparer le train",
    },
    ["item-name"] = {
        ["armored-locomotive-mk1"]="Locomotive blindée",
        ["minigun-platform-mk1"]="Plateforme avec tourelle mitrailleuse Vulcan",
        ["minigun-platform-mk2"]="Plateforme avec double tourelle mitrailleuse Vulcan",
        ["shotgun-platform-mk1"]="Plateforme avec canon Storm",
        ["shotgun-platform-mk2"]="Plateforme avec double canon Storm",
        ["cannon-platform-mk1"]="Plateforme avec tourelle d'artillerie Rainmetal",
        ["cannon-platform-mk2"]="Plateforme avec tourelle d'artillerie Cyclops",
        ["rocket-platform-mk1"]="Plateforme avec tourelle lance-missiles Hurricane",
        ["rocket-platform-mk2"]="Plateforme avec tourelle lance-missiles Swingfire",
        ["flamethrower-platform-mk1"]="Plateforme avec tourelle lance-flammes Incinerator",
        ["flamethrower-platform-mk2"]="Plateforme avec double tourelle lance-flammes Incinerator",
        ["radar-platform-mk1"]="Plateforme avec radar",
        ["searchlight-platform-mk1"]="Plateforme avec lampe de recherche",
        ["repair-platform-mk1"]="Plateforme avec bras de réparation",
    },
    ["item-description"] = {
        ["armored-locomotive-mk1"]="Plus lent et plus lourd mais idéal pour broyer les ennemis les plus coriaces",
        ["minigun-platform-mk1"]="Cadence de tir rapide. Proche et moyenne portée",
        ["minigun-platform-mk2"]="Cadence de tir rapide. Proche et moyenne portée",
        ["shotgun-platform-mk1"]="Cadence de tir moyenne. À courte portée seulement. Dispersion des balles",
        ["cannon-platform-mk1"]="Cadence de tir moyenne. Proche et moyenne portée. Les munitions explosives ne sont pas recommandées",
        ["cannon-platform-mk2"]="Cadence de tir lente. Longue portée. Les munitions explosives sont recommandées pour les bâtiments dotés d'un filtre de cible.",
        ["rocket-platform-mk1"]="Cadence de tir rapide. Proche et moyenne portée. Les munitions explosives ne sont pas recommandées",
        ["rocket-platform-mk2"]="Cadence de tir lente. Longue portée. Les munitions explosives sont recommandées pour les bâtiments dotés d'un filtre de cible.",
        ["flamethrower-platform-mk1"]="Cadence de tir moyenne. Portée rapprochée uniquement. Dégâts de type feu",
        ["flamethrower-platform-mk2"]="Cadence de tir moyenne. Portée rapprochée uniquement. Dégâts de type feu",
        ["radar-platform-mk1"]="Révèle le secteur de la carte actuelle du train",
        ["searchlight-platform-mk1"]="À courte distance seulement. Source de lumière. S'active lorsque des ennemis sont à proximité",
        ["repair-platform-mk1"]="Utilise des packs de réparation pour réparer le train",
    },
    ["technology-name"] = {
        ["armored-train-mk1"]="Train blindé MK1",
        ["armored-train-mk2"]="Train blindé MK2",
        ["armored-train-cannon"]="Tourelle d'artillerie pour train blindé",
        ["armored-train-rocket"]="Tourelle lance-missiles pour train blindé",
        ["armored-train-flamethrower"]="Tourelle lance-flammes pour train blindé",
        ["armored-train-radar"]="Radar pour train blindé",
        ["armored-train-searchlight"]="Lampe de recherche pour train blindé",
    },
    ["technology-description"] = {
    }
    -------------------------
}
