return {
    ---------------
    --base(doublons).cfg
    ["achievement-description"] = {
        ["computer-age-1"]="Produire 500 processeurs par heure.",
        ["computer-age-2"]="Produire 1000 processeurs par heure.",
        ["computer-age-3"]="Produire 5k de processeurs par heure.",
        ["smoke-me-a-kipper-i-will-be-back-for-breakfast"]="Lancez une fusée dans l'espace.",
    },
    ["achievement-name"] = {
        ["computer-age-1"]="L'âge de l'informatique 1",
        ["computer-age-2"]="L'âge de l'informatique 2",
        ["computer-age-3"]="L'âge de l'informatique 3",
        ["smoke-me-a-kipper-i-will-be-back-for-breakfast"]="Par le saint hareng ! Je serai de retour pour le petit déj'",
    },
    ["controls"] = {
        ["give-spidertron-remote"]="Télécommande de Spidertron",
    },
    ["entity-description"] = {
        ["beacon"]="Transmet l'effet des modules aux entités amicales proches. Les effets de transmission se cumulent avec des rendements décroissants.",
        ["cargo-landing-pad"]="Après le lancement d'une fusée, tous les produits des objets lancés atterriront ici.",
        ["cargo-pod"]="Livre des objets depuis la fusée des sciences spatiales jusqu'à l'aire d'atterrissage cargo.",
        ["cargo-pod-container"]="",
        ["infinity-chest"]="",
        ["nuclear-reactor"]="Utilise des barres d'uranium pour générer de la chaleur. La production de chaleur augmente lorsqu'il est adjacent à d'autres réacteurs.",
        ["offshore-pump"]="Pompe un liquide d'une étendue d'eau.",
        ["pump"]="",
        ["rocket-silo"]="Utilisé pour construire et lancer une fusée pour gagner la partie.",
        ["solar-panel"]="Pendant la journée, il produit 100% de la puissance de sortie et descend à 0% la nuit.",
        ["steam-turbine"]="Consomme de la vapeur pour produire de l’énergie électrique.",
    },
    ["entity-name"] = {
        ["assembling-machine-1"]="Machine d'assemblage",
        ["assembling-machine-2"]="Machine d'assemblage rapide",
        ["assembling-machine-3"]="Machine d'assemblage très rapide",
        ["beacon"]="Diffuseur de modules",
        ["behemoth-worm-corpse"]="Cadavre de ver géant",
        ["biter-spawner"]="Nid de déchiqueteurs",
        ["biter-spawner-corpse"]="Cadavre de nid de déchiqueteurs",
        ["boiler"]="Chaudière",
        ["bulk-inserter"]="Bras robotisé haute capacité",
        ["burner-inserter"]="Bras robotisé thermique",
        ["character"]="Personnage",
        ["electric-furnace"]="Four électrique",
        ["express-loader"]="Chargeur express",
        ["express-splitter"]="Répartiteur express",
        ["express-transport-belt"]="Convoyeur express",
        ["express-underground-belt"]="Convoyeur souterrain express",
        ["fast-inserter"]="Bras robotisé rapide",
        ["fast-loader"]="Chargeur rapide",
        ["fast-splitter"]="Répartiteur rapide",
        ["fast-transport-belt"]="Convoyeur rapide",
        ["fast-underground-belt"]="Convoyeur souterrain rapide",
        ["gate"]="Porte",
        ["gun-turret"]="Tourelle mitrailleuse",
        ["inserter"]="Bras robotisé",
        ["lab"]="Laboratoire",
        ["lane-splitter"]="Répartiteur de ligne",
        ["laser-turret"]="Tourelle laser",
        ["loader"]="Chargeur",
        ["nuclear-reactor"]="Réacteur nucléaire",
        ["pipe"]="Tuyau",
        ["pipe-to-ground"]="Tuyau souterrain",
        ["small-electric-pole"]="Petit poteau électrique",
        ["small-lamp"]="Lampe",
        ["solar-panel"]="Panneau solaire",
        ["spidertron"]="Spidertron",
        ["spitter-spawner"]="Nid de cracheurs",
        ["splitter"]="Répartiteur",
        ["steel-furnace"]="Four en acier",
        ["stone-wall"]="Mur",
        ["transport-belt"]="Convoyeur",
        ["underground-belt"]="Convoyeur souterrain",
    },
    ["equipment-name"] = {
        ["fission-reactor-equipment"]="Réacteur à fission portatif",
        ["solar-panel-equipment"]="Panneau solaire portatif",
    },
    ["fuel-category-name"] = {
        ["chemical"]="Combustible",
    },
    ["item-description"] = {
        ["hazard-concrete"]="",
        ["landfill"]="Peut être placé sur l'eau pour créer un terrain sur lequel vous pouvez construire.",
        ["refined-concrete"]="",
        ["refined-hazard-concrete"]="",
        ["solar-panel-equipment"]="Fournit de l'énergie pour les modules d'armure.",
        ["space-science-pack"]="Utilisés dans les laboratoires pour faire des recherches. Obtenus en lançant des satellites dans l'espace.",
        ["spidertron-remote"]="",
    },
    ["item-group-name"] = {
        ["combat"]="Combat",
        ["enemies"]="Ennemis",
    },
    ["item-name"] = {
        ["advanced-circuit"]="Circuit électronique avancé",
        ["barrel"]="Baril",
        ["cannon-shell"]="Obus",
        ["copper-plate"]="Plaque de cuivre",
        ["electric-engine-unit"]="Élément de moteur électrique",
        ["electronic-circuit"]="Circuit électronique",
        ["engine-unit"]="Élément de moteur",
        ["explosive-cannon-shell"]="Obus explosif",
        ["explosive-uranium-cannon-shell"]="Obus explosif à uranium",
        ["firearm-magazine"]="Chargeur",
        ["heavy-armor"]="Armure lourde",
        ["iron-plate"]="Plaque de fer",
        ["lab"]="Laboratoire",
        ["laser-turret"]="Tourelle laser",
        ["light-armor"]="Armure légère",
        ["modular-armor"]="Armure modulaire",
        ["piercing-rounds-magazine"]="Chargeur de munitions perforantes",
        ["power-armor"]="Armure de puissance",
        ["power-armor-mk2"]="Armure de puissance MK2",
        ["processing-unit"]="Processeur",
        ["rocket-launcher"]="Lance-missiles",
        ["spidertron-remote"]="Télécommande de Spidertron",
        ["steel-plate"]="Plaque d'acier",
        ["tank-cannon"]="Canon du tank",
        ["tank-flamethrower"]="Lance-flamme du véhicule",
        ["tank-machine-gun"]="Mitrailleuse de véhicule",
        ["uranium-cannon-shell"]="Obus d'uranium",
        ["uranium-fuel-cell"]="Barre d'uranium",
    },
    ["shortcut"] = {
        ["make-spidertron-remote"]="Fabriquer une télécommande de Spidertron",
    },
    ["technology-description"] = {
        ["advanced-circuit"]="Des circuits intégrés plus avancés.",
        ["automation"]="Technologie clé pour la production automatisée en masse.",
        ["automation-2"]="Machines d'assemblages capables de traiter des ingrédients fluides.",
        ["automation-3"]="Machines d'assemblages capables de traiter des fluides, avec davantage de vitesse et d'emplacements de modules.",
        ["battery-equipment"]="À placer dans une armure. Accumule l'excès d'énergie pour un usage ultérieur.",
        ["battery-mk2-equipment"]="À placer dans une armure. Accumule une grande quantité d'énergie pour un usage ultérieur.",
        ["belt-immunity-equipment"]="Équipement à insérer dans votre armure afin que les convoyeurs ne puissent pas vous déplacer.",
        ["bulk-inserter"]="Bras robotisés qui peuvent déplacer plusieurs objets du même type à la fois.",
        ["effect-transmission"]="Le diffuseur de modules transmet l'effet des modules aux entités amicales proches. Les effets de transmission se cumulent avec des rendements décroissants.",
        ["electric-engine"]="Convertit l’électricité en mouvement mécanique.",
        ["electronics"]="Composants électroniques pour le traitement basique du signal.",
        ["energy-shield-equipment"]="A placer dans une armure. Absorbe les dégâts subis.",
        ["energy-shield-mk2-equipment"]="À placer dans une armure. Absorbe une grande quantité des dégâts subis.",
        ["engine"]="Convertit le carburant en mouvement mécanique. Une composante essentielle pour tous les véhicules.",
        ["exoskeleton-equipment"]="À placer dans une armure. Augmente la vitesse de déplacement. Vous pouvez en équiper plusieurs à la fois.",
        ["fission-reactor-equipment"]="À placer dans une armure pour fournir de l'énergie aux autres équipements.",
        ["flammables"]="Développement de carburants plus efficaces et de combustibles plus agressifs.",
        ["heavy-armor"]="Armure lourde pour plus de protection.",
        ["landfill"]="Peut être placé sur l'eau pour créer un terrain sur lequel vous pouvez construire.",
        ["laser-shooting-speed"]="Augmente la vitesse de tir des armes lasers.",
        ["laser-weapons-damage"]="Augmente les dégâts des armes à énergie et des rayons laser.",
        ["modular-armor"]="Armure disposant d'une petite grille pour les modules d'équipement qui vous fournissent des bonus uniques. La porter augmente également la taille de votre inventaire.",
        ["night-vision-equipment"]="Équipement à insérer dans votre armure afin de mieux voir la nuit.",
        ["nuclear-fuel-reprocessing"]="Le processus de retraitement des barres d'uranium épuisées pour créer de l'uranium-238.",
        ["personal-roboport-equipment"]="Insérer dans l'armure pour permettre aux robots de construction de fonctionner à partir de votre inventaire.",
        ["personal-roboport-mk2-equipment"]="Équipement à insérer dans votre armure pour permettre à beaucoup de robots de construction de fonctionner à partir de votre inventaire.",
        ["physical-projectile-damage"]="Augmente les dégâts des armes à projectiles, tourelles et robots défenseurs.",
        ["power-armor"]="Armure disposant d'une grande grille d'équipement et proposant un agrandissement de l'inventaire.",
        ["power-armor-mk2"]="Armure disposant d'une énorme grille d'équipement et offrant une taille d'inventaire accrue.",
        ["railway"]="Transport à grande échelle sur de longues distances.",
        ["rocket-silo"]="Permet de lancer une fusée dans l’espace et de gagner la partie.",
        ["solar-energy"]="Source d'énergie électrique gratuite, ne fonctionnant cependant que le jour.",
        ["solar-panel-equipment"]="À placer dans une armure. Fournit de l'énergie aux autres équipements, mais ne fonctionne pas la nuit.",
        ["steam-power"]="",
        ["stronger-explosives"]="Augmente les dégâts des armes explosives.",
        ["tank"]="Véhicule offensif puissant sur lequel de nombreux équipements et armes peuvent être installés.",
        ["weapon-shooting-speed"]="Augmente la vitesse de tir de la plupart des armes à projectiles.",
    },
    ["technology-name"] = {
        ["advanced-circuit"]="Circuit électronique avancé",
        ["automation"]="Automatisation",
        ["automation-science-pack"]="Pack de science d'automatisation",
        ["electric-engine"]="Moteur électrique",
        ["electric-mining-drill"]="Foreuse électrique",
        ["electronics"]="Électronique",
        ["engine"]="Moteur",
        ["gun-turret"]="Tourelle",
        ["heavy-armor"]="Armure lourde",
        ["inserter-capacity-bonus"]="Bonus de capacité des bras robotisés",
        ["laser-turret"]="Tourelle laser",
        ["laser-weapons-damage"]="Dégâts des armes à énergie",
        ["modular-armor"]="Armure modulaire",
        ["oil-processing"]="Raffinage du pétrole",
        ["power-armor"]="Armure de puissance",
        ["power-armor-mk2"]="Armure de puissance MK2",
        ["railway"]="Chemin de fer",
        ["robotics"]="Robotique",
        ["solar-energy"]="Énergie solaire",
        ["solar-panel-equipment"]="Panneau solaire portatif",
        ["spidertron"]="Spidertron",
        ["stronger-explosives"]="Explosifs avancés",
        ["uranium-processing"]="Procédé d'enrichissement de l'uranium",
        ["weapon-shooting-speed"]="Vitesse de tir des armes",
    },
    ["tile-description"] = {
        ["water-green"]="",
    },
    ["tile-name"] = {
        ["lab-white"]="Sol de laboratoire blanc",
        ["stone-path"]="Chemin en pierre",
        ["water-green"]="Eau verte",
    },
    ["virtual-signal-name"] = {
        ["signal-minus"]="Moins",
        ["signal-percent"]="Pour cent",
        ["signal-plus"]="Plus",
        ["signal-slash"]="Barre oblique",
        ["signal-speed"]="Vitesse",
    }
    -------------------------
}
