return {
    ---------------
    --Big-Monsters.cfg
    ["entity-name"] = {
        ["bm-large-tunnel"]="Grand tunnel",
        ["bm-spawner"]="Trou souterrain",
        ["bm-spawner-corpse"]="Reste d'un trou souterrain",
        ["biterzilla1"]="Géant de l'enfer",
        ["biterzilla2"]="Géant bleu",
        ["biterzilla3"]="Bête des roches",
        ["bm-motherbiterzilla"]="Mère nourricière",
        ["bm-motherbiterzilla-corpse"]="Corps de mère nourricière",
        ["maf-giant-acid-spitter"]="Monstrueux cracheur d'acide",
        ["maf-giant-acid-spitter-corpse"]="Corps de monstrueux cracheur d'acide",
        ["maf-behemoth-worm-turret"]="Monstrueux ver géant",
        ["maf-colossal-worm-turret"]="Monstrueux ver colossal",
        ["behemoth-worm-corpse"]="Corps de monstrueux ver géant",
        ["colossal-worm-corpse"]="Corps de monstrueux ver colossal",
        ["maf-giant-fire-spitter"]="Monstrueux cracheur de feu",
        ["bm-worm-boss-acid-shooter"]="Monstrueux ver cracheur de feu",
        ["bm-worm-boss-fire-shooter"]="Monstrueux ver cracheur d'acide",
        ["bm-volcano"]="Volcan",
        ["bm_fake_human_machine_gunner"]="Humain avec mitrailleuse",
        ["bm_fake_human_melee"]="Humain avec pioche",
        ["bm_fake_human_pistol_gunner"]="Humain avec pistolet",
        ["bm_fake_human_sniper"]="Humain avec fusil de précision",
        ["bm_fake_human_laser"]="Humain avec fusil laser",
        ["bm_fake_human_electric"]="Humain avec fusil électrique",
        ["bm_fake_human_erocket"]="Humain avec lance-missiles",
        ["bm_fake_human_rocket"]="Humain avec lance-missiles",
        ["bm_fake_human_grenade"]="Humain avec grenade",
        ["bm_fake_human_cluster_grenade"]="Humain avec grenade à fragmentation",
        ["bm_fake_human_nuke_rocket"]="Humain avec bombe atomique",
        ["bm_fake_human_cannon"]="Humain avec canon",
        ["bm_fake_human_cannon_explosive"]="Humain avec canon explosif",
        ["bm_fake_human_flamethrower"]="Pirate avec lance-flammes",
        ["bm_fake_human_boss_melee"]="Boss avec pioche",
        ["bm_fake_human_boss_machine_gunner"]="Boss avec mitrailleuse",
        ["bm_fake_human_boss_pistol_gunner"]="Boss avec pistolet",
        ["bm_fake_human_boss_sniper"]="Boss avec fusil de précision",
        ["bm_fake_human_boss_laser"]="Boss avec fusil laser",
        ["bm_fake_human_boss_electric"]="Boss avec fusil électrique",
        ["bm_fake_human_boss_erocket"]="Boss avec lance-missiles",
        ["bm_fake_human_boss_rocket"]="Boss avec lance-missiles",
        ["bm_fake_human_boss_grenade"]="Boss avec grenade",
        ["bm_fake_human_boss_cluster_grenade"]="Boss avec grenade à fragmentation",
        ["bm_fake_human_boss_nuke_rocket"]="Boss avec bombe atomique",
        ["bm_fake_human_boss_cannon_explosive"]="Boss avec canon explosif",
        ["bm_fake_human_boss_flamethrower"]="Boss avec tourelle lance-flammes",
        ["bm_fake_human_ultimate_boss_cannon"]="Boss ultime avec canon",
        ["maf_flying_saucer"]="Soucoupe volante",
    },
    ["entity-description"] = {
        ["bm-volcano"]="Ce volcan a projeté des torrents de feu tout autour de lui. Ces éruptions vont durer un certain temps",
    },
    ["item-name"] = {
        ["flying-saucer-laser-cannon"]="Canon laser pour soucoupe volante",
        ["flying-saucer-laser-ammo"]="Munitions laser pour soucoupe volante",
        ["maf-small-atomic-rocket"]="Petit missile atomique",
    }
    -------------------------
}
