return {
    ---------------
    --BlackMarket2.cfg
    ["technology-name"] = {
        ["black-market-item"]="Coffres de négociation Black Market 2",
        ["black-market-fluid"]="Réservoirs de stockage de négociation Black Market 2",
        ["black-market-energy"]="Accumulateurs de négociation Black Market 2",
        ["black-market-mk2"]="Mise à niveau 2 de Black Market 2",
        ["black-market-mk3"]="Mise à niveau 3 de Black Market 2",
        ["black-market-mk4"]="Mise à niveau 4 de Black Market 2",
    },
    ["technology-description"] = {
        ["black-market-item"]="Vendez et achetez des objets sur le marché en utilisant des coffres de négociation",
        ["black-market-fluid"]="Vendez et achetez des fluides sur le marché en utilisant des réservoirs de stockage de négociation",
        ["black-market-energy"]="Vendez et achetez de l'électricité sur le marché en utilisant des accumulateurs de négociation",
        ["black-market-mk2"]="Débloque les interfaces de vente/achat MK2, le coffre MK2, l'accumulateur MK2 et le réservoir de stockage MK2.",
        ["black-market-mk3"]="Débloque les interfaces de vente/achat MK3, le coffre MK3, l'accumulateur MK3 et le réservoir de stockage MK3.",
        ["black-market-mk4"]="Débloque les interfaces de vente/achat MK4, le coffre MK4, l'accumulateur MK4 et le réservoir de stockage MK4.",
    },
    ["item-group-name"] = {
        ["black-market-group"]="Black Market",
    },
    ["entity-name"] = {
        ["trader-chst-buy"]="Coffre de négociation (achat)",
        ["trader-chst-sel"]="Coffre de négociation (vente)",
        ["trader-tank-buy"]="Réservoirs de stockage de négociation (achat)",
        ["trader-tank-sel"]="Réservoirs de stockage de négociation (vente)",
        ["trader-accu-buy"]="Accumulateurs de négociation (achat)",
        ["trader-accu-sel"]="Accumulateurs de négociation (vente)",
        ["trader-chst-buy-mk2"]="Coffre de négociation MK2 (achat)",
        ["trader-chst-sel-mk2"]="Coffre de négociation MK2 (vente)",
        ["trader-tank-buy-mk2"]="Réservoirs de stockage de négociation MK2 (achat)",
        ["trader-tank-sel-mk2"]="Réservoirs de stockage de négociation MK2 (vente)",
        ["trader-accu-buy-mk2"]="Accumulateurs de négociation MK2 (achat)",
        ["trader-accu-sel-mk2"]="Accumulateurs de négociation MK2 (vente)",
        ["trader-chst-buy-mk3"]="Coffre de négociation MK3 (achat)",
        ["trader-chst-sel-mk3"]="Coffre de négociation MK3 (vente)",
        ["trader-tank-buy-mk3"]="Réservoirs de stockage de négociation MK3 (achat)",
        ["trader-tank-sel-mk3"]="Réservoirs de stockage de négociation MK3 (vente)",
        ["trader-accu-buy-mk3"]="Accumulateurs de négociation MK3 (achat)",
        ["trader-accu-sel-mk3"]="Accumulateurs de négociation MK3 (vente)",
        ["trader-chst-buy-mk4"]="Coffre de négociation MK4 (achat)",
        ["trader-chst-sel-mk4"]="Coffre de négociation MK4 (vente)",
        ["trader-tank-buy-mk4"]="Réservoirs de stockage de négociation MK4 (achat)",
        ["trader-tank-sel-mk4"]="Réservoirs de stockage de négociation MK4 (vente)",
        ["trader-accu-buy-mk4"]="Accumulateurs de négociation MK4 (achat)",
        ["trader-accu-sel-mk4"]="Accumulateurs de négociation MK4 (vente)",
    },
    ["entity-description"] = {
        ["trader-chst-buy"]="Ce coffre reçoit les objets achetés sur le marché.",
        ["trader-chst-sel"]="Tout objet placé dans ce coffre est vendu sur le marché.",
        ["trader-tank-buy"]="Ce réservoir de stockage reçoit le fluide acheté sur le marché.",
        ["trader-tank-sel"]="Tout fluide placé dans ce réservoir de stockage est vendu sur le marché.",
        ["trader-accu-buy"]="Cet accumulateur reçoit de l'électricité achetée sur le marché (il ne prend jamais d'électricité sur votre réseau).",
        ["trader-accu-sel"]="L'électricité qui entre dans cet accumulateur est vendue sur le marché (si elle n'est pas vendue, elle retourne progressivement sur le réseau).",
        ["trader-chst-buy-mk2"]="Ce coffre reçoit les objets achetés sur le marché.",
        ["trader-chst-sel-mk2"]="Tout objet placé dans ce coffre est vendu sur le marché.",
        ["trader-tank-buy-mk2"]="Ce réservoir de stockage reçoit le fluide acheté sur le marché.",
        ["trader-tank-sel-mk2"]="Tout fluide placé dans ce réservoir de stockage est vendu sur le marché.",
        ["trader-accu-buy-mk2"]="Cet accumulateur reçoit de l'électricité achetée sur le marché (il ne prend jamais d'électricité sur votre réseau).",
        ["trader-accu-sel-mk2"]="L'électricité qui entre dans cet accumulateur est vendue sur le marché (si elle n'est pas vendue, elle retourne progressivement sur le réseau).",
        ["trader-chst-buy-mk3"]="Ce coffre reçoit les objets achetés sur le marché.",
        ["trader-chst-sel-mk3"]="Tout objet placé dans ce coffre est vendu sur le marché.",
        ["trader-tank-buy-mk3"]="Ce réservoir de stockage reçoit le fluide acheté sur le marché.",
        ["trader-tank-sel-mk3"]="Tout fluide placé dans ce réservoir de stockage est vendu sur le marché.",
        ["trader-accu-buy-mk3"]="Cet accumulateur reçoit de l'électricité achetée sur le marché (il ne prend jamais d'électricité sur votre réseau).",
        ["trader-accu-sel-mk3"]="L'électricité qui entre dans cet accumulateur est vendue sur le marché (si elle n'est pas vendue, elle retourne progressivement sur le réseau).",
        ["trader-chst-buy-mk4"]="Ce coffre reçoit les objets achetés sur le marché.",
        ["trader-chst-sel-mk4"]="Tout objet placé dans ce coffre est vendu sur le marché.",
        ["trader-tank-buy-mk4"]="Ce réservoir de stockage reçoit le fluide acheté sur le marché.",
        ["trader-tank-sel-mk4"]="Tout fluide placé dans ce réservoir de stockage est vendu sur le marché.",
        ["trader-accu-buy-mk4"]="Cet accumulateur reçoit de l'électricité achetée sur le marché (il ne prend jamais d'électricité sur votre réseau).",
        ["trader-accu-sel-mk4"]="L'électricité qui entre dans cet accumulateur est vendue sur le marché (si elle n'est pas vendue, elle retourne progressivement sur le réseau).",
    },
    ["item-name"] = {
        ["ucoin"]="Upièce",
        ["trader-chst-buy"]="Coffre de négociation (achat)",
        ["trader-chst-sel"]="Coffre de négociation (vente)",
        ["trader-tank-buy"]="Réservoirs de stockage de négociation (achat)",
        ["trader-tank-sel"]="Réservoirs de stockage de négociation (vente)",
        ["trader-accu-buy"]="Accumulateurs de négociation (achat)",
        ["trader-accu-sel"]="Accumulateurs de négociation (vente)",
        ["trader-chst-buy-mk2"]="Coffre de négociation MK2 (achat)",
        ["trader-chst-sel-mk2"]="Coffre de négociation MK2 (vente)",
        ["trader-tank-buy-mk2"]="Réservoirs de stockage de négociation MK2 (achat)",
        ["trader-tank-sel-mk2"]="Réservoirs de stockage de négociation MK2 (vente)",
        ["trader-accu-buy-mk2"]="Accumulateurs de négociation MK2 (achat)",
        ["trader-accu-sel-mk2"]="Accumulateurs de négociation MK2 (vente)",
        ["trader-chst-buy-mk3"]="Coffre de négociation MK3 (achat)",
        ["trader-chst-sel-mk3"]="Coffre de négociation MK3 (vente)",
        ["trader-tank-buy-mk3"]="Réservoirs de stockage de négociation MK3 (achat)",
        ["trader-tank-sel-mk3"]="Réservoirs de stockage de négociation MK3 (vente)",
        ["trader-accu-buy-mk3"]="Accumulateurs de négociation MK3 (achat)",
        ["trader-accu-sel-mk3"]="Accumulateurs de négociation MK3 (vente)",
        ["trader-chst-buy-mk4"]="Coffre de négociation MK4 (achat)",
        ["trader-chst-sel-mk4"]="Coffre de négociation MK4 (vente)",
        ["trader-tank-buy-mk4"]="Réservoirs de stockage de négociation MK4 (achat)",
        ["trader-tank-sel-mk4"]="Réservoirs de stockage de négociation MK4 (vente)",
        ["trader-accu-buy-mk4"]="Accumulateurs de négociation MK4 (achat)",
        ["trader-accu-sel-mk4"]="Accumulateurs de négociation MK4 (vente)",
    },
    ["virtual-signal-name"] = {
        ["signal-market-auto-all"]="Négociations en mode automatique : marche(>1)/arrêt(=1)/ignorer(=0)",
        ["signal-market-auto-sel"]="Négociations en mode vente automatique : marche(>1)/arrêt(=1)/ignorer(=0)",
        ["signal-market-auto-buy"]="Négociations en mode achat automatique : marche(>1)/arrêt(=1)/ignorer(=0)",
    }
    -------------------------
}
