return {
    ---------------
    --bobmodules.cfg
    ["item-name"] = {
        ["bob-pollution-clean-module-1"]="Module de filtration de la pollution 1",
        ["bob-pollution-clean-module-2"]="Module de filtration de la pollution 2",
        ["bob-pollution-clean-module-3"]="Module de filtration de la pollution 3",
        ["bob-pollution-clean-module-4"]="Module de filtration de la pollution 4",
        ["bob-pollution-clean-module-5"]="Module de filtration de la pollution 5",
        ["bob-pollution-create-module-1"]="Module de production de pollution 1",
        ["bob-pollution-create-module-2"]="Module de production de pollution 2",
        ["bob-pollution-create-module-3"]="Module de production de pollution 3",
        ["bob-pollution-create-module-4"]="Module de production de pollution 4",
        ["bob-pollution-create-module-5"]="Module de production de pollution 5",
        ["bob-god-module"]="Module divin",
        ["bob-god-module-productivity"]="Module divin (productivité)",
        ["bob-god-module-quality"]="Module divin (qualitéy)",
        ["bob-beacon-2"]="Diffuseur 2",
        ["bob-beacon-3"]="Diffuseur 3",
        ["bob-module-case"]="Boîtier de module",
        ["bob-module-contact"]="Connexion du module",
        ["bob-module-circuit-board"]="Carte principale du module",
        ["bob-module-processor-board"]="Carte de module de base",
        ["bob-module-processor-board-2"]="Carte logique de module",
        ["bob-module-processor-board-3"]="Carte processeur de module",
        ["bob-speed-processor"]="Carte de module de vitesse de base",
        ["bob-effectivity-processor"]="Carte de module d'efficacité de base",
        ["bob-productivity-processor"]="Carte de module de productivité de base",
        ["bob-pollution-clean-processor"]="Carte de module de filtration de la pollution de base",
        ["bob-pollution-create-processor"]="Carte de module de production de pollution de base",
        ["bob-quality-processor"]="Carte de module de qualité de base",
        ["bob-speed-processor-2"]="Carte logique de module de vitesse",
        ["bob-effectivity-processor-2"]="Carte logique de module d'efficacité",
        ["bob-productivity-processor-2"]="Carte logique de module de productivité",
        ["bob-pollution-clean-processor-2"]="Carte logique de module de filtration de la pollution",
        ["bob-pollution-create-processor-2"]="Carte logique de module de production de pollution",
        ["bob-quality-processor-2"]="Carte logique de module de qualité",
        ["bob-speed-processor-3"]="Carte processeur de module de vitesse",
        ["bob-effectivity-processor-3"]="Carte processeur de module d'efficacité",
        ["bob-productivity-processor-3"]="Carte processeur de module de productivité",
        ["bob-pollution-clean-processor-3"]="Carte processeur de module de filtration de la pollution",
        ["bob-pollution-create-processor-3"]="Carte processeur de module de production de pollution",
        ["bob-quality-processor-3"]="=Carte processeur de module de qualité",
    },
    ["technology-name"] = {
        ["bob-pollution-clean-module"]="Module de filtration de la pollution",
        ["bob-pollution-create-module"]="Module de productivité de pollution",
        ["bob-god-module"]="Module divin",
    },
    ["entity-name"] = {
        ["bob-beacon-2"]="Diffuseur 2",
        ["bob-beacon-3"]="Diffuseur 3",
    },
    ["item-group-name"] = {
        ["bobmodules"]="Modules",
    },
    ["tips-and-tricks-item-description"] = {
    }
    -------------------------
}
