return {
    ---------------
    --bobpower.cfg
    ["technology-name"] = {
        ["bob-electric-pole"]="Poteaux électriques",
        ["bob-electric-substation"]="Sous-stations",
        ["bob-fluid-generator"]="Générateur à combustion de fluides",
        ["bob-hydrazine-generator"]="Générateur à l'hydrazine",
        ["bob-oil-boiler"]="Chaudière à combustion de fluides",
        ["bob-nuclear-power"]="Énergie nucléaire",
        ["bob-heat-pipe"]="Conduite de chaleur",
        ["bob-burner-reactor"]="Source de chaleur thermique",
        ["bob-fluid-reactor"]="Source de chaleur à combustion de fluides",
    },
    ["technology-description"] = {
        ["bob-electric-pole"]="De meilleurs poteaux électriques",
        ["bob-electric-substation"]="De meilleures sous-stations",
        ["bob-boiler"]="Fabrication et l'amélioration des chaudières.",
        ["bob-steam-engine"]="Fabrication et l'amélioration des générateurs électriques à vapeur.",
        ["bob-oil-boiler"]="Fabrication et l'amélioration des chaudières à combustion de fluides.",
        ["bob-heat-exchanger"]="Fabrication et l'amélioration des échangeurs de chaleur",
        ["bob-steam-turbine"]="Amélioration des générateurs électriques à vapeur avec des turbines. L'énergie produite par les turbines sera utilisée en priorité.",
        ["bob-heat-pipe"]="Les conduites de chaleur, une méthode pour amener la chaleur aux alentours et l'utiliser comme source d'énergie.",
    },
    ["entity-name"] = {
        ["bob-solar-panel-small"]="Petit panneau solaire",
        ["bob-solar-panel-large"]="Grand panneau solaire",
        ["bob-solar-panel-small-2"]="Petit panneau solaire 2",
        ["bob-solar-panel-2"]="Panneau solaire 2",
        ["bob-solar-panel-large-2"]="Grand panneau solaire 2",
        ["bob-solar-panel-small-3"]="Petit panneau solaire 3",
        ["bob-solar-panel-3"]="Panneau solaire 3",
        ["bob-solar-panel-large-3"]="Grand panneau solaire 3",
        ["bob-large-accumulator"]="Accumulateur haute capacité",
        ["bob-fast-accumulator"]="Accumulateur rapide",
        ["bob-slow-accumulator"]="Accumulateur lent",
        ["bob-large-accumulator-2"]="Accumulateur haute capacité 2",
        ["bob-fast-accumulator-2"]="Accumulateur rapide 2",
        ["bob-slow-accumulator-2"]="Accumulateur lent 2",
        ["bob-large-accumulator-3"]="Accumulateur haute capacité 3",
        ["bob-fast-accumulator-3"]="Accumulateur rapide 3",
        ["bob-slow-accumulator-3"]="Accumulateur lent 3",
        ["bob-oil-boiler"]="Chaudière à combustion de fluides",
        ["bob-medium-electric-pole-2"]="Poteau électrique moyen 2",
        ["bob-medium-electric-pole-3"]="Poteau électrique moyen 3",
        ["bob-medium-electric-pole-4"]="Poteau électrique moyen 4",
        ["big-electric-pole-2"]="Grand poteau électrique 2",
        ["big-electric-pole-3"]="Grand poteau électrique 3",
        ["big-electric-pole-4"]="Grand poteau électrique 4",
        ["bob-substation-2"]="Poste électrique 2",
        ["bob-substation-3"]="Poste électrique 3",
        ["bob-substation-4"]="Poste électrique 4",
        ["bob-fluid-generator"]="Générateur à combustion de fluides",
        ["bob-fluid-generator-2"]="Générateur à combustion de fluides 2",
        ["bob-fluid-generator-3"]="Générateur à combustion de fluides 3",
        ["bob-hydrazine-generator"]="Générateur à l'hydrazine",
        ["bob-burner-generator"]="Générateur électrique thermique",
        ["bob-burner-reactor"]="Source de chaleur thermique",
        ["bob-burner-reactor-2"]="Source de chaleur thermique 2",
        ["bob-fluid-reactor"]="Source de chaleur à combustion de fluides",
        ["bob-fluid-reactor-2"]="Source de chaleur à combustion de fluides 2",
    },
    ["entity-description"] = {
        ["bob-oil-boiler"]="Brûle un combustible liquide pour transformer l'eau en vapeur.",
        ["steam-turbine"]="Consomme de la vapeur pour créer de l'énergie électrique. A une priorité accrue sur le réseau électrique.",
    },
    ["item-name"] = {
        ["bob-solar-panel-small"]="Petit panneau solaire",
        ["bob-solar-panel-large"]="Grand panneau solaire",
        ["bob-solar-panel-small-2"]="Petit panneau solaire 2",
        ["bob-solar-panel-2"]="Panneau solaire 2",
        ["bob-solar-panel-large-2"]="Grand panneau solaire 2",
        ["solar-panel-small-3"]="Petit panneau solaire 3",
        ["solar-panel-3"]="Panneau solaire 3",
        ["solar-panel-large-3"]="Grand panneau solaire 3",
        ["bob-large-accumulator"]="Accumulateur haute capacité",
        ["bob-fast-accumulator"]="Accumulateur rapide",
        ["bob-basic-accumulator-2"]="Accumulateur de base 2",
        ["bob-large-accumulator-2"]="Accumulateur haute capacité 2",
        ["bob-fast-accumulator-2"]="Accumulateur rapide 2",
        ["bob-basic-accumulator-3"]="Accumulateur de base 3",
        ["bob-large-accumulator-3"]="Accumulateur haute capacité 3",
        ["bob-fast-accumulator-3"]="Accumulateur rapide 3",
        ["bob-medium-electric-pole-2"]="Poteau électrique moyen 2",
        ["bob-medium-electric-pole-3"]="Poteau électrique moyen 3",
        ["bob-medium-electric-pole-4"]="Poteau électrique moyen 4",
        ["bob-big-electric-pole-2"]="Grand poteau électrique 2",
        ["bob-big-electric-pole-3"]="Grand poteau électrique 3",
        ["bob-big-electric-pole-4"]="Grand poteau électrique 4",
        ["bob-substation-2"]="Poste électrique 2",
        ["bob-substation-3"]="Poste électrique 3",
        ["bob-substation-4"]="Poste électrique 4",
        ["bob-fluid-generator"]="Générateur à combustion de fluides",
        ["bob-fluid-generator-2"]="Générateur à combustion de fluides 2",
        ["bob-fluid-generator-3"]="Générateur à combustion de fluides 3",
        ["bob-hydrazine-generator"]="Générateur à l'hydrazine",
    }
    -------------------------
}
