return {
    ---------------
    --Clowns-Nuclear.cfg
    ["item-name"] = {
        ["thorium-ore"]="Minerai de thorium",
        ["thorium-232"]="Thorium 232",
        ["thorium-fuel-cell"]="Pile à combustible au thorium",
        ["used-up-thorium-fuel-cell"]="Pile à combustible au thorium usagée",
        ["critical-mass"]="Masse critique",
        ["thermonuclear-bomb"]="Bombe thermonucléaire",
        ["artillery-shell-thermonuclear"]="Obus d'artillerie thermonucléaire tactique",
        ["artillery-shell-nuclear"]="Obus d'artillerie nucléaire tactique",
        ["plutonium-239"]="Plutonium 239",
        ["20pc-uranium"]="Uranium (20% U235)",
        ["35pc-uranium"]="Uranium (35% U235, Qualité combustible)",
        ["45pc-uranium"]="Uranium (45% U235)",
        ["55pc-uranium"]="Uranium (55% U235)",
        ["65pc-uranium"]="Uranium (65% U235)",
        ["70pc-uranium"]="Uranium (70% U235)",
        ["75pc-uranium"]="Uranium (75% U235)",
    },
    ["recipe-name"] = {
        ["thorium-processing"]="Traitement du thorium",
        ["thorium-fuel-cell"]="Piles à combustible au thorium",
        ["thorium-nuclear-fuel-reprocessing"]="Retraitement du combustible nucléaire au thorium",
        ["mixed-oxide"]="Oxyde mixte uranium-plutonium",
        ["thorium-mixed-oxide"]="Oxyde mixte thorium-plutonium",
        ["thermonuclear-bomb"]="Bombe thermonucléaire",
        ["artillery-shell-thermonuclear"]="Obus d'artillerie thermonucléaire tactique",
        ["artillery-shell-nuclear"]="Obus d'artillerie nucléaire tactique",
        ["plutonium-atomic-bomb"]="Bombe atomique au plutonium",
        ["clowns-centrifuging-80pc"]="Centrifugation de l'uranium jusqu'à 80 % d'enrichissement",
        ["clowns-centrifuging-75pc"]="Centrifugation de l'uranium jusqu'à 75 % d'enrichissement",
        ["clowns-centrifuging-70pc"]="Centrifugation de l'uranium jusqu'à 70 % d'enrichissement",
        ["clowns-centrifuging-65pc"]="Centrifugation de l'uranium jusqu'à 65 % d'enrichissement",
        ["clowns-centrifuging-55pc"]="Centrifugation de l'uranium jusqu'à 55 % d'enrichissement",
        ["clowns-centrifuging-45pc"]="Centrifugation de l'uranium jusqu'à 45 % d'enrichissement",
        ["clowns-centrifuging-35pc"]="Centrifugation de l'uranium jusqu'à 35 % d'enrichissement",
        ["clowns-centrifuging-20pc-ore"]="Centrifugation de l'uranium jusqu'à 20 % d'enrichissement",
        ["clowns-centrifuging-20pc-hexafluoride"]="Centrifugation de l'uranium jusqu'à 20 % d'enrichissement",
        ["depleted-uranium-reprocessing"]="Retraitement de l'uranium appauvri",
    },
    ["technology-name"] = {
        ["thorium-nuclear-power"]="Énergie nucléaire au thorium",
        ["thorium-nuclear-fuel-reprocessing"]="Retraitement du combustible nucléaire au thorium",
        ["mixed-oxide-fuel"]="Combustible à oxyde mixte",
        ["thermonuclear-bomb"]="Bombe thermonucléaire",
        ["nuclear-fuel"]="Combustible nucléaire",
        ["radiothermal-fuel"]="Combustible radiothermique",
    },
    ["technology-description"] = {
        ["thorium-nuclear-power"]="",
        ["thorium-nuclear-fuel-reprocessing"]="Le processus de retraitement du combustible nucléaire au thorium usagé permet de créer des isotopes précieux.",
        ["mixed-oxide-fuel"]="L'utilisation du plutonium comme matière fissile permet d'augmenter l'efficacité du combustible.",
        ["thermonuclear-bomb"]="Maintenant je suis devenu la mort, le destructeur des mondes",
        ["radiothermal-fuel"]="Sources de chaleur de très longue durée synthétisées à partir d'éléments hautement radioactifs.",
    }
    -------------------------
}
