return {
    ---------------
    --creative-mod.cfg
    ["entity-name"] = {
        ["creative-mod_creative-chest"]="Coffre du mode créatif",
        ["creative-mod_new-creative-chest"]="Coffre du mode créatif",
        ["creative-mod_creative-provider-chest"]="Coffre d'approvisionnement logistique du mode créatif",
        ["creative-mod_new-creative-provider-chest"]="Coffre d'approvisionnement logistique du mode créatif",
        ["creative-mod_inf-requester-chest"]="Coffre de demandes logistique infini",
        ["creative-mod_inf-provider-chest"]="Coffre d'approvisionnement logistique infini",
        ["creative-mod_autofill-requester-chest"]="Coffre de demandes logistique à remplissage automatique",
        ["creative-mod_new-autofill-requester-chest"]="Coffre de demandes logistique à remplissage automatique",
        ["creative-mod_duplicating-chest"]="Coffre de duplication",
        ["creative-mod_duplicating-provider-chest"]="Coffre de duplication d'approvisionnement logistique",
        ["creative-mod_void-requester-chest"]="Coffre de demandes logistique à suppression automatique",
        ["creative-mod_void-chest"]="Coffre à suppression automatique",
        ["creative-mod_void-storage-chest"]="Coffre de stockage logistique à suppression automatique",
        ["creative-mod_super-loader"]="Super-chargeur",
        ["creative-mod_super-loader2"]="Super-chargeur 1x1",
        ["creative-mod_creative-cargo-wagon"]="Wagon de marchandises du mode créatif",
        ["creative-mod_duplicating-cargo-wagon"]="Wagon de marchandises de duplication",
        ["creative-mod_void-cargo-wagon"]="Wagon de marchandises à suppression automatique",
        ["creative-mod_super-logistic-robot"]="Super-robot logistique",
        ["creative-mod_super-construction-robot"]="Super-robot de construction",
        ["creative-mod_super-roboport"]="Super-roboport",
        ["creative-mod_fluid-source"]="Source de fluide",
        ["creative-mod_fluid-void"]="Suppresseur de fluide",
        ["creative-mod_super-boiler"]="Super-chaudière",
        ["creative-mod_super-cooler"]="Super-refroidisseur",
        ["creative-mod_configurable-super-boiler"]="Super-chaudière configurable ",
        ["creative-mod_heat-source"]="Source de chaleur",
        ["creative-mod_heat-void"]="Suppresseur de chaleur",
        ["creative-mod_item-source"]="Source de matière",
        ["creative-mod_duplicator"]="Duplicateur de matière",
        ["creative-mod_item-void"]="Suppresseur de matière",
        ["creative-mod_random-item-source"]="Source d'objet aléatoire",
        ["creative-mod_creative-lab"]="Laboratoire du mode créatif",
        ["creative-mod_void-lab"]="Laboratoire à suppression automatique ",
        ["creative-mod_active-electric-energy-interface-output"]="Interface de l’énergie électrique active (Sortie)",
        ["creative-mod_passive-electric-energy-interface"]="Interface de l’énergie électrique passive",
        ["creative-mod_active-electric-energy-interface-input"]="Interface de l’énergie électrique active (Entrée)",
        ["creative-mod_energy-source"]="Source d'énergie active",
        ["creative-mod_passive-energy-source"]="Source d'énergie passive",
        ["creative-mod_energy-void"]="Suppresseur d'énergie active ",
        ["creative-mod_passive-energy-void"]="Suppresseur d'énergie passive",
        ["creative-mod_super-electric-pole"]="Super-poteau électrique",
        ["creative-mod_super-substation"]="Super-sous-station électrique",
        ["creative-mod_super-radar"]="Super-radar",
        ["creative-mod_super-radar-2"]="Super-radar 2",
        ["creative-mod_alien-attractor-proxy-small"]="Petit attracteur d'extraterrestres",
        ["creative-mod_alien-attractor-proxy-medium"]="Attracteur d'extraterrestres moyen",
        ["creative-mod_alien-attractor-proxy-large"]="Grand attracteur d'extraterrestres",
        ["creative-mod_super-beacon"]="Super-diffuseur de modules",
    },
    ["entity-description"] = {
        ["creative-mod_duplicating-chest"]="Coffre en acier qui duplique l’objet dans son premier emplacement.\nSupprime le contenu lors de la suppression.",
        ["creative-mod_duplicating-provider-chest"]="Coffre d'approvisionnement logistique passif qui duplique l’objet dans son premier emplacement.\nEfface le contenu lors de la suppression.",
        ["creative-mod_void-requester-chest"]="Coffre de demandes logistique qui supprime les objets.\nSupprime le contenu lors de la suppression.",
        ["creative-mod_void-chest"]="Coffre qui supprime les objets.\nSupprime le contenu lors de la suppression.",
        ["creative-mod_void-storage-chest"]="Coffre de stockage logistique qui supprime les objets.\nSupprime le contenu lors de la suppression.",
        ["creative-mod_duplicating-cargo-wagon"]="Wagon de marchandises qui duplique l’objet dans son premier emplacement.\nSupprime le contenu lors de la suppression.",
        ["creative-mod_void-cargo-wagon"]="Wagon de marchandises qui supprime les objets.\nSupprime le contenu lors de la suppression.",
        ["creative-mod_super-logistic-robot"]="Robot logistique extrêmement rapide et sans énergie avec une charge utile élevée. On peut mettre jusqu'à 1k robots dans chaque pile.",
        ["creative-mod_super-construction-robot"]="Robot de construction extrêmement rapide et sans énergie avec une charge utile élevée. On peut mettre jusqu'à 1k robots dans chaque pile.",
        ["creative-mod_super-roboport"]="N'a pas vraiment besoin d'énergie malgré le signal d'alarme.",
        ["creative-mod_fluid-source"]="Peut produire des fluides en illimité. (Vous devrez activer les recettes du mode créatif avant de pouvoir choisir la recette du fluide.)",
        ["creative-mod_fluid-void"]="Annule les fluides entrants.",
        ["creative-mod_super-boiler"]="Réchauffe rapidement les fluides jusqu'à la température maximale.",
        ["creative-mod_super-cooler"]="Refroidit rapidement les fluides jusqu'à la température par défaut.",
        ["creative-mod_configurable-super-boiler"]="Réchauffe rapidement les liquides ou les refroidit jusqu'à la température définie. Il a un emplacement à carburant, mais n’en a pas besoin pour fonctionner.",
        ["creative-mod_heat-source"]="Génère de la chaleur gratuitement. C'est toujours à 1000 °C.",
        ["creative-mod_heat-void"]="Absorbe la chaleur gratuitement. C'est toujours à 0 °C.",
        ["creative-mod_duplicator"]="Duplique l'objet ou le fluide devant lui.",
        ["creative-mod_creative-lab"]="Capable de générer tous les packs de sciences disponibles dans le jeu pour son propre usage.\nSupprime le contenu lors de la suppression.",
        ["creative-mod_void-lab"]="Possibilité de faire des recherches illimitées tout en utilisant les packs de science dans le laboratoire.",
        ["creative-mod_energy-source"]="Produit une énergie illimitée sur le réseau avant que les accumulateurs ne produisent de l'énergie.",
        ["creative-mod_passive-energy-source"]="Fonctionne uniquement lorsque les autres générateurs ne peuvent pas produire suffisamment d'électricité.",
        ["creative-mod_energy-void"]="Supprime l'énergie, rendant d'autres entités non-fonctionnelles.",
        ["creative-mod_passive-energy-void"]="Absorbe constamment l'énergie excédentaire du réseau sans affecter d'autres entités.",
        ["creative-mod_super-beacon"]="Super-grande surface utile. Accepte également les modules de productivité. N'a pas vraiment besoin d'énergie malgré le signal d'alarme.",
    },
    ["technology-name"] = {
        ["creative-mod_void-technology"]="Technologie du néant",
    },
    ["technology-description"] = {
        ["creative-mod_void-technology"]="Une technologie qui (espérons-le) ne finit jamais.",
    },
    ["equipment-name"] = {
        ["creative-mod_super-fusion-reactor-equipment"]="Super-réacteur à fusion portatif",
        ["creative-mod_super-personal-roboport-equipment"]="Super-roboport personnel",
    },
    ["item-name"] = {
        ["creative-mod_energy-absorption"]="Absorbeur d'énergie",
        ["creative-mod_magic-wand-creator"]="Baguette magique - Créatrice",
        ["creative-mod_magic-wand-healer"]="Baguette magique - Guérisseuse",
        ["creative-mod_magic-wand-modifier"]="Baguette magique - Modificatrice",
        ["creative-mod_alien-attractor-small"]="Petit attracteur d'extraterrestres",
        ["creative-mod_alien-attractor-medium"]="Attracteur d'extraterrestres moyens",
        ["creative-mod_alien-attractor-large"]="Grand attracteur d'extraterrestres",
        ["creative-mod_super-speed-module"]="Super-module de vitesse",
        ["creative-mod_super-effectivity-module"]="Super-module d'efficacité",
        ["creative-mod_super-productivity-module"]="Super-module de production",
        ["creative-mod_super-clean-module"]="Super-module de propreté",
        ["creative-mod_super-slow-module"]="Super-module de ralentissement",
        ["creative-mod_super-consumption-module"]="Super-module de consommation",
        ["creative-mod_super-pollution-module"]="Super-module de pollution",
    },
    ["item-description"] = {
        ["creative-mod_energy-absorption"]="Absorbe l'énergie du réseau. (Vous ne devriez pas garder cet objet. Enlevez-le dès que possible !)",
        ["creative-mod_alien-attractor-small"]="Posez-le sur le sol et 5 extraterrestres seront attirés pour y construire un nid. Bien que cela puisse prendre un certain temps pour eux de se regrouper et de bouger.",
        ["creative-mod_alien-attractor-medium"]="Posez-le sur le sol et 20 extraterrestres seront attirés pour y construire un nid. Bien que cela puisse prendre un certain temps pour eux de se regrouper et de bouger.",
        ["creative-mod_alien-attractor-large"]="Posez-le sur le sol et 100 extraterrestres seront attirés pour y construire un nid. Bien que cela puisse prendre un certain temps pour eux de se regrouper et de bouger.",
        ["creative-mod_super-speed-module"]="Augmente massivement la vitesse de la machine.",
        ["creative-mod_super-effectivity-module"]="Réduit massivement la consommation d'énergie de la machine. La consommation d'énergie minimale est de 20%.",
        ["creative-mod_super-productivity-module"]="Augmente massivement la productivité de la machine. Peut être utilisé dans toutes les recettes.",
        ["creative-mod_super-clean-module"]="Réduit massivement la pollution de la machine. La pollution minimale est de 20%.",
        ["creative-mod_super-slow-module"]="Réduit massivement la vitesse de la machine. La vitesse minimale est de 20%.",
        ["creative-mod_super-consumption-module"]="Augmente massivement la consommation d'énergie de la machine.",
        ["creative-mod_super-pollution-module"]="Augmente massivement la pollution de la machine.",
        ["creative-mod_super-fusion-reactor-equipment"]="Génère une puissance illimitée pour votre équipement.",
        ["creative-mod_super-personal-roboport-equipment"]="Prend en charge un grand nombre de robots. Grand rayon de construction. Peut recharger les robots instantanément sans utiliser aucune énergie.",
    },
    ["item-group-name"] = {
        ["creative-mod_creative-tools"]="Outils créatifs",
    }
    -------------------------
}
