return {
    ---------------
    --EditorExtensions.cfg
    ["controls"] = {
        ["ee-toggle-map-editor"]="Activer l'éditeur de cartes",
    },
    ["entity-description"] = {
        ["ee-aggregate-chest"]="Contient tous les objets du jeu.",
        ["ee-infinity-accumulator"]="Produit, absorbe ou stocke une quantité configurable d'énergie électrique.",
        ["ee-infinity-cargo-wagon"]="Crée ou détruit des objets en utilisant des filtres d'objets personnalisables (identique au coffre infini).",
        ["ee-infinity-chest"]="Crée ou détruit des objets en utilisant des filtres d'objets personnalisables.",
        ["ee-infinity-combinator"]="Surveille les signaux logiques grâce à un affichage hautement personnalisable.",
        ["ee-infinity-fluid-wagon"]="Crée ou détruit des fluides en utilisant des filtres de fluides personnalisables (identique au tuyau infini).",
        ["ee-infinity-heat-pipe"]="Crée ou détruit une quantité de chaleur configurable.",
        ["ee-infinity-loader"]="Crée ou détruit des éléments sur un convoyeur en utilisant des filtres personnalisables.",
        ["ee-infinity-loader-dummy-combinator"]="Ceci représente l'emplacement d'un ancien chargeur infini. Les signaux représentent les filtres de convoyeur qui se trouvaient sur ce chargeur infini.",
        ["ee-infinity-pipe"]="Crée ou détruit des fluides en utilisant des filtres de fluides personnalisables.",
        ["ee-linked-chest"]="Partage son inventaire avec d'autres coffres liés sur le même canal.",
        ["ee-performance-warning"]="Peut causer des problèmes de performances si on en abuse, à utiliser avec parcimonie !",
        ["ee-super-beacon"]="Diffuseur avec une énorme zone d'effet sans avoir besoin d'énergie. Accepte tous les modules, y compris la productivité.",
        ["ee-super-construction-robot"]="Robot de construction incroyablement rapide et sans avoir besoin d'énergie.",
        ["ee-super-electric-pole"]="Poteau électrique avec une grande portée de fil.",
        ["ee-super-inserter"]="Bras robotisé filtrable hyper-rapide de grande capacité et sans consommation d'énergie.",
        ["ee-super-lab"]="Laboratoire incroyablement rapide et sans consommation d'énergie.",
        ["ee-super-locomotive"]="Locomotive incroyablement rapide. N'a pas besoin de carburant pour fonctionner !",
        ["ee-super-logistic-robot"]="Robot logistique incroyablement rapide et sans consommation d'énergie.",
        ["ee-super-pump"]="Pompe sans consommation d'énergie avec une vitesse de pompage réglable.",
        ["ee-super-radar"]="Radar sans consommation d'énergie avec une zone de révélation massive.",
        ["ee-super-roboport"]="Roboport sans consommation d'énergie avec recharge instantanée et une très grande zone de couverture.",
        ["ee-super-substation"]="Sous-station avec zone d'alimentation et portée de câble énormes.",
    },
    ["entity-name"] = {
        ["ee-aggregate-chest"]="Coffre global",
        ["ee-aggregate-chest-passive-provider"]="Coffre d'approvisionnement logistique passif global",
        ["ee-infinity-accumulator"]="Accumulateur infini",
        ["ee-infinity-cargo-wagon"]="Wagon de marchandises infini",
        ["ee-infinity-chest-active-provider"]="Coffre d'approvisionnement logistique actif infini",
        ["ee-infinity-chest-buffer"]="Coffre tampon infini",
        ["ee-infinity-chest"]="Coffre infini",
        ["ee-infinity-chest-passive-provider"]="Coffre d'approvisionnement logistique passif infini",
        ["ee-infinity-chest-requester"]="Coffre de demandes logistiques infini",
        ["ee-infinity-chest-storage"]="Coffre de stockage logistique infini",
        ["ee-infinity-combinator"]="Circuit logique infini",
        ["ee-infinity-fluid-wagon"]="Wagon-citerne infini",
        ["ee-infinity-heat-pipe"]="Conduite de chaleur infinie",
        ["ee-infinity-loader-chest"]="Chargeur infini",
        ["ee-infinity-loader-dummy-combinator"]="Chargeur infini factice (NE FONCTIONNE PAS)",
        ["ee-infinity-loader"]="Chargeur infini",
        ["ee-infinity-pipe"]="Tuyau infini",
        ["ee-infinity-wagon-chest"]="Wagon de marchandises infini",
        ["ee-infinity-wagon-pipe"]="Wagon-citerne infini",
        ["ee-linked-belt"]="Convoyeur lié",
        ["ee-linked-chest"]="Coffre lié",
        ["ee-super-beacon"]="Super-diffuseur de modules",
        ["ee-super-construction-robot"]="Super-robot de construction",
        ["ee-super-electric-pole"]="Super-poteau électrique",
        ["ee-super-inserter"]="Super-bras robotisé",
        ["ee-super-lab"]="Super-laboratoire",
        ["ee-super-locomotive"]="Super-locomotive",
        ["ee-super-logistic-robot"]="Super-robot logistique",
        ["ee-super-pump"]="Super-pompe",
        ["ee-super-radar"]="Super-radar",
        ["ee-super-roboport"]="Super-roboport",
        ["ee-super-substation"]="Super-poste électrique",
    },
    ["equipment-name"] = {
        ["ee-infinity-fission-reactor-equipment"]="Réacteur à fission infini",
        ["ee-super-battery-equipment"]="Super-batterie personnelle",
        ["ee-super-energy-shield-equipment"]="Super-bouclier énergétique",
        ["ee-super-exoskeleton-equipment"]="Super-exosquelette",
        ["ee-super-night-vision-equipment"]="Super-vision nocturne",
        ["ee-super-personal-roboport-equipment"]="Super-roboport personnel",
    },
    ["fluid-description"] = {
        ["ee-super-pump-speed-fluid"]="Si vous voyez ceci, faites demi-tour immédiatement ! Il est utilisé par Editor Extensions pour contrôler la vitesse de la super-pompe, et n'a aucune utilité ailleurs.",
    },
    ["fluid-name"] = {
        ["ee-super-pump-speed-fluid"]="Superfluide",
    },
    ["item-description"] = {
        ["ee-infinity-fission-reactor-equipment"]="Génère une puissance virtuellement illimitée pour votre équipement.",
        ["ee-linked-belt"]="Transporte instantanément les objets vers un autre convoyeur relié.",
        ["ee-super-battery-equipment"]="Batterie ridiculement massive.",
        ["ee-super-clean-module"]="Diminue massivement la pollution de la machine. La pollution minimale est de 20%.",
        ["ee-super-dirty-module"]="Augmente massivement la pollution des machines.",
        ["ee-super-efficiency-module"]="Diminue massivement la consommation d'énergie de la machine. La consommation d'énergie minimale est de 20 %.",
        ["ee-super-energy-shield-equipment"]="Bouclier énergétique incroyablement surpuissant, qui vous rend pratiquement immortel.",
        ["ee-super-exoskeleton-equipment"]="Exosquelette très petit et très rapide.",
        ["ee-super-fuel"]="Du combustible nucléaire qui dure à peu près éternellement.",
        ["ee-super-inefficiency-module"]="Augmente massivement la consommation d'énergie de la machine.",
        ["ee-super-night-vision-equipment"]="Vision nocturne parfaite, vous pouvez voir comme en plein jour..",
        ["ee-super-personal-roboport-equipment"]="Robport personnel avec une zone de construction et une capacité de robot énormes.",
        ["ee-super-productivity-module"]="Augmente massivement la productivité des machines.",
        ["ee-super-slow-module"]="Diminue massivement la vitesse de la machine. La vitesse minimale est de 20%.",
        ["ee-super-speed-module"]="Augmente massivement la vitesse de la machine.",
    },
    ["item-group-name"] = {
        ["ee-tools"]="Outils de test",
    },
    ["item-name"] = {
        ["ee-infinity-accumulator"]="Accumulateur infini",
        ["ee-super-clean-module"]="Super-module nettoyant",
        ["ee-super-dirty-module"]="Super-module polluant",
        ["ee-super-efficiency-module"]="Super-module d'efficacité",
        ["ee-super-fuel"]="Super-carburant",
        ["ee-super-inefficiency-module"]="Super-module d'inefficacité",
        ["ee-super-productivity-module"]="Super-module de productivité",
        ["ee-super-slow-module"]="Super-module de lenteur",
        ["ee-super-speed-module"]="Super-module de vitesse",
    },
    ["shortcut-name"] = {
        ["ee-toggle-map-editor"]="Activer l'éditeur de cartes",
    }
    -------------------------
}
