return {
    ---------------
    --ev-refining.cfg
    ["item-name"] = {
        ["jaw-crusher"]="Broyeur à mâchoires",
        ["electrolytic-unit"]="Unité électrolytique",
        ["HDPE-alloy"]="Alliage de polyéthylène haute densité",
        ["enriched-coal"]="Charbon enrichi",
        ["coal-coke"]="Coke de charbon",
        ["coal-dust"]="Poussière de charbon",
        ["coal-clump"]="Amas de charbon",
        ["coal-chunk"]="Bloc de charbon",
        ["crusher1"]="Broyeur de minerais",
        ["crusher2"]="Broyeur de minerais 2",
        ["crusher3"]="Broyeur de minerais 3",
        ["echamber1"]="Chambre d'enrichissement",
        ["echamber2"]="Chambre d'enrichissement 2",
        ["echamber3"]="Chambre d'enrichissement 3",
        ["pchamber1"]="Chambre de purification",
        ["pchamber2"]="Chambre de purification 2",
    },
    ["item-description"] = {
        ["jaw-crusher"]="Dispositif mécanique qui utilise la force de compression pour briser les grosses roches en morceaux plus petits et plus faciles à manipuler.",
    },
    ["recipe-name"] = {
        ["steel-dust-smelting"]="Plaque d'acier (à partir de la poussière)",
        ["advanced-steel-processing"]="Traitement avancé de l'acier",
        ["coal-dust"]="Poussière de charbon - Broyage du charbon",
        ["coal-dust-enrichment"]="Enrichissement des poussières de charbon",
        ["coal-clump"]="Amas de charbon - Enrichissement du charbon",
        ["coal-clump-enrichment"]="Enrichissement des amas de charbon",
        ["advanced-coal-crushing"]="Broyage avancé du charbon",
        ["advanced-coal-enriching"]="Enrichissement avancé du charbon",
        ["coal-chunk"]="Bloc de charbon - Centrifugation des amas de charbon",
        ["coal-chunk-enrichment"]="Enrichissement des blocs de charbon",
        ["rocket-fuel-from-coal-chunk"]="Combustible pour fusée à partir de blocs de charbon",
        ["plastics-from-enriched-coal"]="Plastique à partir de charbon enrichi",
        ["explosives-from-enriched-coal"]="Explosifs à partir de charbon enrichi",
        ["grenades-from-enriched-coal"]="Grenades à partir de charbon enrichi",
        ["enriched-coal-from-carbon"]="Charbon enrichi à partir de carbone",
        ["stone-to-gravel"]="Graviers - Broyage de la pierre",
        ["gravel-to-brick"]="Brique de pierre - Fonte du gravier",
        ["gravel-landfill"]="Remblais - Pierres et graviers",
        ["gravel-to-sand"]="Sable fin - Broyage du gravier",
        ["sand-to-brick"]="Brique en pierre - Fonte du sable fin",
        ["concrete-finishing"]="Béton - Traitement du béton",
        ["sand-landfill"]="Remblais - Gravier et sable",
    },
    ["entity-name"] = {
        ["crusher1"]="Broyeur de minerais",
        ["crusher2"]="Broyeur de minerais 2",
        ["crusher3"]="Broyeur de minerais 3",
        ["echamber1"]="Chambre d'enrichissement",
        ["echamber2"]="Chambre d'enrichissement 2",
        ["echamber3"]="Chambre d'enrichissement 3",
        ["pchamber1"]="Chambre de purification",
        ["pchamber2"]="Chambre de purification 2",
    },
    ["technology-name"] = {
        ["base-ore-processing"]="Traitement du minerai de base",
        ["advanced-ore-processing"]="Traitement avancé du minerai",
        ["elite-ore-processing"]="Traitement du minerai d'élite",
        ["ultimate-ore-processing"]="Traitement ultime du minerai",
        ["advanced-coal-processing"]="Traitement avancé du charbon",
        ["coal-enriching"]="Enrichissement du charbon",
        ["ore-crushing-productivity"]="Productivité du broyage du minerai",
        ["ore-enriching-productivity"]="Productivité de l'enrichissement du minerai",
        ["advanced-holmium-processing"]="Traitement avancé du holmium",
    },
    ["technology-description"] = {
        ["base-ore-processing"]="Les broyeurs peuvent augmenter considérablement le rendement normal du minerai en broyant mécaniquement le minerai brut en poussières plus petites et plus faciles à cuire.",
        ["ultimate-ore-processing"]="La découverte de la science spatiale et toutes les recherches effectuées dans le domaine des minéraux nous permettent de créer des machines nettement plus efficaces et plus puissantes.",
        ["ore-crushing-productivity"]="Les nouvelles planètes et découvertes nous permettent d'améliorer les techniques de raffinage du minerai.",
        ["ore-enriching-productivity"]="Les nouvelles planètes et découvertes nous permettent d'améliorer les techniques de raffinage du minerai.",
        ["advanced-holmium-processing"]="Nous sommes désormais en mesure de traiter le minerai de holmium de la même manière que le fer et le cuivre.",
    }
    -------------------------
}
