return {
    ---------------
    --kry-inserters.cfg
    ["entity-name"] = {
        ["burner-long-inserter"]="Bras robotisé thermique long",
        ["burner-slow-filter-inserter"]="Bras robotisé thermique lent filtrable",
        ["burner-filter-inserter"]="Bras robotisé thermique filtrable",
        ["burner-bulk-inserter"]="Bras robotisé thermique filtrable haute capacité",
        ["burner-stack-inserter"]="Bras robotisé thermique empileur",
        ["burner-stack-filter-inserter"]="Bras robotisé thermique filtrable empileur",
        ["long-slow-filter-inserter"]="Bras robotisé long filtrable",
        ["long-pipe-inserter"]="Bras robotisé long à vapeur",
        ["pipe-filter-inserter"]="Bras robotisé à vapeur filtrable",
        ["long-fast-inserter"]="Bras robotisé long rapide",
        ["long-bulk-inserter"]="Bras robotisé long haute capacité",
        ["long-stack-inserter"]="Bras robotisé long empileur",
        ["long-filter-inserter"]="Bras robotisé long filtrable",
        ["long-fast-filter-inserter"]="Bras robotisé long rapide filtrable",
        ["long-stack-filter-inserter"]="Bras robotisé long filtrable empileur",
        ["long-bob-steam-inserter"]="Bras robotisé long à vapeur",
        ["long-bob-express-inserter"]="Bras robotisé long express",
        ["long-bob-express-bulk-inserter"]="Bras robotisé long express haute capacité",
        ["long-kr-superior-inserter"]="Bras robotisé long supérieur",
        ["long-kr-superior-filter-inserter"]="Bras robotisé long supérieur filtrable",
        ["long-gold-inserter"]="Bras électrique long",
        ["long-fast-2-inserter"]="Bras robotisé long rapide MK2",
        ["long-fast-3-inserter"]="Bras robotisé long rapide MK3",
        ["long-stack-2-inserter"]="Bras robotisé long empileur MK2",
        ["long-stack-filter-2-inserter"]="Bras robotisé long empileur filtrable MK2",
        ["long-nuclear-inserter"]="Bras robotisé long à énergie nucléaire",
        ["long-nuclear-filter-inserter"]="Bras robotisé long filtrable à énergie nucléaire",
        ["long-nuclear-stack-inserter"]="Bras robotisé long empileur à énergie nucléaire",
        ["long-nuclear-stack-filter-inserter"]="Bras robotisé long empileur filtrable à énergie nucléaire",
        ["long-plutonium-inserter"]="Bras robotisé long au plutonium",
        ["long-plutonium-filter-inserter"]="Bras robotisé long filtrable au plutonium",
        ["long-plutonium-stack-inserter"]="Bras robotisé long empileur au plutonium",
        ["long-plutonium-stack-filter-inserter"]="Bras robotisé long filtrable empileur au plutonium",
        ["nutrient-long-inserter"]="Bras long à nutriments",
    },
    ["entity-description"] = {
    },
    ["item-name"] = {
        ["burner-long-inserter"]="Bras robotisé thermique long",
        ["burner-filter-inserter"]="Bras robotisé thermique filtrable",
        ["burner-stack-inserter"]="Bras robotisé thermique empileur",
        ["burner-stack-filter-inserter"]="Bras robotisé thermique filtrable empileur",
        ["long-slow-filter-inserter"]="Bras robotisé long filtrable",
        ["long-pipe-inserter"]="Bras robotisé long à vapeur",
        ["pipe-filter-inserter"]="Bras robotisé à vapeur filtrable",
        ["long-fast-inserter"]="Bras robotisé long rapide",
        ["long-bulk-inserter"]="Bras robotisé long haute capacité",
        ["long-stack-inserter"]="Bras robotisé long empileur",
        ["long-filter-inserter"]="Bras robotisé long filtrable",
        ["long-fast-filter-inserter"]="Bras robotisé long rapide filtrable",
        ["long-stack-filter-inserter"]="Bras robotisé long filtrable empileur",
        ["long-bob-steam-inserter"]="Bras robotisé long à vapeur",
        ["long-bob-express-inserter"]="Bras robotisé long express",
        ["long-bob-express-nulk-inserter"]="Bras robotisé long express haute capacité",
        ["long-kr-superior-inserter"]="Bras robotisé long supérieur",
        ["long-kr-superior-filter-inserter"]="Bras robotisé long supérieur filtrable",
        ["long-gold-inserter"]="Bras électrique long",
        ["long-fast-inserter-2"]="Bras robotisé long rapide MK2",
        ["long-fast-inserter-3"]="Bras robotisé long rapide MK3",
        ["long-stack-inserter-2"]="Bras robotisé long empileur MK2",
        ["long-stack-filter-inserter-2"]="Bras robotisé long filtrable empileur MK2",
        ["long-nuclear-inserter"]="Bras robotisé long à énergie nucléaire",
        ["long-nuclear-filter-inserter"]="Bras robotisé long filtrable à énergie nucléaire",
        ["long-nuclear-stack-inserter"]="LBras robotisé long empileur à énergie nucléaire",
        ["long-nuclear-stack-filter-inserter"]="Bras robotisé long empileur filtrable à énergie nucléaire",
        ["long-plutonium-inserter"]="Bras robotisé long au plutonium",
        ["long-plutonium-filter-inserter"]="Bras robotisé long filtrable au plutonium",
        ["long-plutonium-stack-inserter"]="Bras robotisé long empileur au plutonium",
        ["long-plutonium-stack-filter-inserter"]="Bras robotisé long filtrable empileur au plutonium",
        ["nutrient-long-inserter"]="Bras long à nutriments",
    },
    ["item-description"] = {
    },
    ["technology-name"] = {
        ["burner-filter"]="Bras robotisé thermique filtrable",
        ["burner-stack"]="Bras robotisé thermique empileur",
        ["burner-stack-filter"]="Bras robotisé thermique filtrable empileur",
        ["DIR-burner-inserter"]="Bras robotisés 0",
    },
    ["technology-description"] = {
        ["burner-filter"]="Bras robotisés thermiques avec possibilité de filtrer les objets",
        ["DIR-burner-inserter"]="Amélioration de vos serviteurs robots : plus intelligents, plus rapides, plus forts.",
        ["long-inserters"]="Des bras robotisés rouges plus longs que les bras robotisés jaunes normaux",
    }
    -------------------------
}
