return {
    ---------------
    --oceanblock.cfg
    ["fluid-name"] = {
        ["hydrogen"]="Hydrogène",
        ["oxygen"]="Oxygènre",
        ["nitrogen"]="Azote",
        ["nitric-acid"]="Acide nitrique",
        ["mineral-water"]="Eau minérale",
        ["slurry"]="Boues",
        ["ferric-solution"]="Solution de fer",
        ["cupric-solution"]="Solution de cuivre",
        ["uranium-hexasulfide"]="Hexasulfure d'uranium",
    },
    ["item-name"] = {
        ["sand"]="Sable",
        ["filter"]="Filtre",
        ["used-filter"]="Filtre usagé",
        ["advanced-processing-unit"]="Processeur avancé",
        ["titanium-ore"]="Minerai de titane",
        ["titanium-powder"]="Poudre de titane",
        ["titanium-plate"]="Plaque de titane",
        ["titansteel-plate"]="Plaque en titane-acier",
        ["titanium-iron-mixture"]="Mélange de titane et de fer",
        ["tungstic-acid"]="Acide tungstique",
    },
    ["recipe-name"] = {
        ["nauvis-scavenging"]="Fouille sur Nauvis",
        ["electrolysis"]="Électrolyse",
        ["mineral-water-crystalization"]="Cristallisation de l'eau minérale",
        ["advanced-electrolysis"]="Électrolyse avancée",
        ["filter-cleaning"]="Nettoyage des filtres",
        ["slurry-filtering-1"]="Filtration des boues 1",
        ["slurry-filtering-2"]="Filtration des boues 2",
        ["fish-breeding"]="Élevage de poissons",
        ["fish-oil"]="Huile de poisson",
        ["advanced-slurry-filtering-for-iron"]="Filtration avancée des boues 1",
        ["advanced-slurry-filtering-for-copper"]="Filtration avancée des boues 2",
        ["ferric-solution-filtering"]="Filtration de la solution de fer",
        ["cupric-solution-filtering"]="Filtration de la solution de cuivre",
        ["landfill-from-sand"]="Remblai à partir de sable",
        ["sand-centrifuging"]="Centrifugation du sable",
        ["sand-dissolving"]="Boues",
        ["sg-charcoal"]="Charbon",
        ["air-separation"]="Séparation de l'air",
        ["low-density-structure-from-titansteel"]="Structure à faible densité à partir de titane et de fer",
        ["vulcanus-scavenging"]="Fouille sur Vulcanus",
        ["tungsten-ore-from-lava"]="Minerai de tungstène provenant de la lave",
        ["stone-from-lava"]="Pierre provenant de la lave",
        ["vulcanus-air-separation"]="Séparation de l'air de Vulcanus",
        ["heavy-oil-filtering"]="Filtration du pétrole lourd",
        ["fulgora-scavenging"]="Fouille sur Fulgora",
        ["stone-melting"]="Fonte de la pierre",
        ["casting-titansteel-plate"]="Coulée de plaques de titane et de fer",
        ["aquilo-air-separation"]="Séparation de l'air sur Aquilo",
        ["chalcopyrite-refining"]="Solution de sulfate mixte",
        ["alternate-nitric-acid"]="Acide nitrique alternatif",
        ["grow-wood-with-atmosphere"]="Cultiver du bois dans l'air ambiant",
    },
    ["technology-name"] = {
        ["ore-productivity"]="Productivité du minerai",
        ["titanium-processing"]="Traitement du titane",
        ["titanium-productivity"]="Productivité du titane",
    },
    ["item-group-name"] = {
        ["oceanblock"]="OceanBlock",
    }
    -------------------------
}
