return {
    ---------------
    --omnimatter.cfg
    ["technology-name"] = {
        ["omnitech-omnium-processing"]="Traitement de l'omnium",
        ["omnitech-base-omnitraction"]="omnitraction de base",
        ["omnitech-omnitractor-electric"]=" omnitracteur électrique",
        ["omnitech-angels-omnium-smelting"]="Fonderie avancée de l'omnium",
        ["omnitech-angels-omnium-iron-alloy-smelting"]="Fonderie de l'omnifer",
        ["omnitech-angels-omnium-steel-alloy-smelting"]="Fonderie de l'omnichalybe",
        ["omnitech-angels-omnium-aluminium-alloy-smelting"]="Fonderie de l'omnilumina",
        ["omnitech-angels-omnium-tungsten-alloy-smelting"]="Fonderie de l'omnifram",
        ["omnitech-omnite-concrete"]="Bétomnium",
    },
    ["technology-description"] = {
        ["omnitech-omnite-concrete"]="Matériau de construction très avancé également utilisé pour les pavements.",
    },
    ["item-group-name"] = {
        ["omnimatter"]="Omnimatière",
        ["omnic-water-distilation"]="Omnilation",
    },
    ["item-name"] = {
        ["omnite"]="Omnite",
        ["crushed-omnite"]="Omnite broyée",
        ["pulverized-omnite"]="Omnite pulvérisé",
        ["stone-crushed"]="Pierre broyée",
        ["pulverized-stone"]="Pierre pulvérisée",
        ["omnicium-plate"]="Plaque d'omnicium",
        ["omnium-plate"]="Plaque d'omnium",
        ["ingot-omnium"]="Lingot d'omnium",
        ["omnite-brick"]="Brique d'omnite",
        ["processed-omnium"]="Omnium traité",
        ["pellet-omnium"]="Granulés d'omnium",
        ["angels-roll-omnium"]="Bobine de feuille d'omniciuim",
        ["omnium-gear-wheel"]="Roue dentée en omnium",
        ["omnium-iron-gear-box"]="Boîte mécanique en fer omnium",
        ["omnium-steel-gear-box"]="Boîte mécanique en acier omnium",
        ["omnium-brass-gear-box"]="Boîte mécanique en laiton omnium",
        ["omnium-titanium-gear-box"]="Boîte mécanique en titane omnium",
        ["omnium-tungsten-gear-box"]="Boîte mécanique en tungstène omnium",
        ["omnium-nitinol-gear-box"]="Boîte mécanique en nitinol omnium",
        ["omnium-iron-alloy"]="Omnifer",
        ["omnium-steel-alloy"]="Omnichalybe",
        ["omnium-aluminium-alloy"]="Omnilumina",
        ["omnium-tungsten-alloy"]="Omnifram",
        ["burner-omniphlog"]="Omniphlogue thermique",
        ["steam-omniphlog"]="Omniphlogue à vapeur",
        ["omnite-concrete"]="Bétomnium",
        ["omnite-refined-concrete"]="Bétomnium raffiné",
    },
    ["item-description"] = {
        ["omnite"]="meep",
    },
    ["recipe-name"] = {
        ["omniston"]="Omniston",
        ["omnic-acid"]="Acide omnique",
        ["burner-omnitractor"]="Omnitracteur thermique",
        ["steam-omnitractor"]="Omnitracteur à vapeur",
        ["omnic-water-purificiation"]="Purification de l'eau omnique",
        ["roll-omnium-casting"]="Bobine de feuille d'omniciuim",
        ["roll-omnium-casting-fast"]="Bobine de feuille d'omniciuim",
        ["pulverize-omnite"]="Omnite pulvérisé",
        ["crushing-omnite"]="Omnite broyée",
        ["pulverized-stone"]="Pierre pulvérisée",
        ["omnisludge"]="Boue d'omni",
        ["crushing-omnite-by-hand"]="Broyage manuel de l'omnite",
        ["omnic-waste-recycling"]="Recyclage des déchets omnique",
    },
    ["recipe-description"] = {
        ["base_impure"]="Niveau d'extraction de base.",
    },
    ["entity-name"] = {
        ["omnite"]="Omnite",
        ["omniston"]="Omniston",
        ["burner-omnitractor"]="Omnitracteur thermique",
        ["steam-omnitractor"]="Omnitracteur à vapeur",
        ["infinite-omnite"]="Omnite à l'infini",
        ["burner-omni-furnace"]="Omnifour",
        ["burner-omniphlog"]="Omniphlogue thermique",
        ["steam-omniphlog"]="Omniphlogue à vapeur",
        ["omnite-brick"]="Brique d'omnite",
        ["omnite-concrete"]="Bétomnium",
        ["omnite-refined-concrete"]="Bétomnium raffiné",
    },
    ["tile-name"] = {
        ["omnite-brick"]="Chemin en omnite",
        ["omnite-concrete"]="Bétomnium",
        ["omnite-refined-concrete"]="Bétomnium raffiné",
    },
    ["fluid-name"] = {
        ["omniston"]="Omniston",
        ["omnic-acid"]="Acide omnique",
        ["omnisludge"]="Boue d'omni",
        ["liquid-molten-omnium"]="Omnium fondu",
        ["molten-omnium-iron-alloy"]="Omnifer fondu",
        ["molten-omnium-steel-alloy"]="Omnichalybe fondu",
        ["molten-omnium-aluminium-alloy"]="Omnilumina fondu",
        ["molten-omnium-tungsten-alloy"]="Omnifram fondu",
        ["omnic-waste"]="Déchets omniques",
        ["omnic-water"]="Eau omnique",
    }
    -------------------------
}
