return {
    ---------------
    --Pacifist.cfg
    ["ammo-category-name"] = {
        ["capture-robot"]="Robot de capture",
        ["railgun"]="Projectile de haute vitesse",
    },
    ["controls"] = {
        ["shoot-enemy"]="Utiliser l'outil",
        ["shoot-selected"]="Utiliser l'outil sur une sélection",
        ["next-weapon"]="Outil suivant",
    },
    ["controls-description"] = {
        ["shoot-enemy"]="Utilise l'outil équipé actuel sur la cible la plus proche du curseur ou, pour certains outils, sur l'emplacement du curseur.",
        ["shoot-selected"]="Utilise l'outil équipé actuel en ciblant ce que vous avez sélectionné ou, pour certains outils, en ciblant l'emplacement du curseur.",
        ["next-weapon"]="Passe à l'outil équipé suivant.",
    },
    ["entity-name"] = {
        ["gun-turret"]="Défense physique à projectiles contre les astéroïdes",
        ["laser-turret"]="Défense laser contre les astéroïdes",
        ["rocket-turret"]="Missile de défense contre les astéroïdes",
        ["railgun-turret"]="Défense à grande vitesse contre les astéroïdes",
        ["gleba-spawner"]="Radeau gluant",
        ["gleba-spawner-small"]="Petit radeau gluant",
        ["gleba-spawner-corpse"]="Vestige de radeau gluant",
        ["gleba-spawner-corpse-small"]="Vestige de petit radeau gluant",
        ["biter-spawner"]="Gisement de spores mutantes",
        ["biter-spawner-corpse"]="Vestige de gisement de spores mutantes",
        ["captive-biter-spawner"]="Gisement de spores maîtrisé",
        ["capture-robot"]="Bio-sonde",
        ["capture-robot-rocket"]="Bio-sonde",
    },
    ["entity-description"] = {
        ["rocket-turret"]="Une défense à longue portée qui tire des missiles.",
        ["railgun-turret"]="Un système de défense électrique à longue portée. Efficace contre les gros astéroïdes.",
        ["captive-biter-spawner"]="La maîtrise de ce gisement nécessite de la nourriture. Il se transformera s'il meurt de faim. Il peut être contrôlé en ciblant le [entity=biter-spawner] avec [item=capture-robot-rocket]",
        ["capture-robot"]="Sonde le [entity=biter-spawner] ciblé et le convertit en un [entity=captive-biter-spawner].",
        ["capture-robot-rocket"]="Sonde le [entity=biter-spawner] ciblé et le convertit en un [entity=captive-biter-spawner].",
    },
    ["item-group-name"] = {
        ["combat"]="Équipement",
        ["enemies"]="Unités",
    },
    ["item-name"] = {
        ["pacifist-grenade"]="Détonateur",
        ["pacifist-abomb"]="Détonateur nucléaire",
        ["light-armor"]="Combinaison de protection",
        ["heavy-armor"]="Combinaison de protection lourde",
        ["modular-armor"]="Combinaison modulaire",
        ["power-armor"]="Combinaison spatiale MK1",
        ["power-armor-mk2"]="Combinaison spatiale MK2",
        ["firearm-magazine"]="Chargeur de projectiles à dégâts physiques",
        ["piercing-rounds-magazine"]="Chargeur de projectiles denses",
        ["laser-turret"]="Défense laser contre les astéroïdes",
        ["railgun-ammo"]="Projectile de haute vitesse",
        ["pentapod-egg"]="Gousse gluante",
        ["rocket-launcher"]="Lanceur de bio-sondes",
        ["captive-biter-spawner"]="Gisement de spores maîtrisé",
        ["capture-robot-rocket"]="Bio-sonde",
        ["biter-egg"]="Échantillon de spores",
        ["capture-robot-capsule"]="Capsule de bio-sonde",
    },
    ["item-description"] = {
        ["capture-robot-rocket"]="Sonde le [entity=biter-spawner] ciblé et le convertit en un [entity=captive-biter-spawner].",
        ["capture-robot-capsule"]="Sonde le [entity=biter-spawner] ciblé et le convertit en un [entity=captive-biter-spawner].",
    },
    ["recipe-name"] = {
        ["nutrients-from-biter-egg"]="Nutriments provenant d'un échantillon de spores",
    },
    ["technology-name"] = {
        ["heavy-armor"]="Combinaison de protection lourde",
        ["modular-armor"]="Combinaison modulaire",
        ["power-armor"]="Combinaison spatiale MK1",
        ["power-armor-mk2"]="Combinaison spatiale MK2",
        ["gun-turret"]="Défense à projectiles physiques contre les astéroïdes",
        ["laser-turret"]="Défense laser contre les astéroïdes",
        ["rocket-turret"]="Missiles de défense contre les astéroïdes",
        ["weapon-shooting-speed"]="Vitesse des projectiles de défense",
        ["laser-weapons-damage"]="Dégâts de la défense laser",
        ["stronger-explosives"]="Dégâts des missiles",
        ["railgun"]="Défense de haute vitesse contre les astéroïdes",
        ["railgun-shooting-speed"]="Vitesse de défense de haute vitesse",
        ["railgun-damage"]="Dégâts des projectiles de haute vitesse",
        ["captive-biter-spawner"]="Gisement de spores maîtrisé",
        ["captivity"]="Bio-sondes",
        ["biter-egg-handling"]="Manipulation des échantillons de spores",
    },
    ["technology-description"] = {
        ["tank"]="Véhicule puissant capable de recevoir des équipements. Utile pour se frayer un chemin à travers les arbres et les rochers.",
        ["spidertron"]="Un véhicule polyvalent capable de traverser des terrains accidentés. Il peut être conduit manuellement ou à l'aide de la télécommande pour Spidertron.",
        ["flammables"]="Développer des carburants plus efficaces.",
        ["heavy-armor"]="Combinaison lourde pour une meilleure protection.",
        ["modular-armor"]="Combinaison avec une petite grille pour les modules d'équipement qui vous donnent des bonus uniques. La porter augmente également la taille de votre inventaire.",
        ["power-armor"]="Combinaison spatiale dotée d'une grande grille d'équipement et d'un bonus de taille d'inventaire.",
        ["power-armor-mk2"]="Combinaison spatiale dotée d'une énorme grille d'équipement et d'un bonus de taille d'inventaire.",
        ["battery-equipment"]="Inséré dans les combinaisons pour stocker l'énergie excédentaire en vue d'une utilisation ultérieure.",
        ["battery-mk2-equipment"]="Inséré dans les combinaisons pour stocker beaucoup d'énergie en vue d'une utilisation ultérieure.",
        ["energy-shield-equipment"]="Inséré dans les combinaisons pour absorber des dégâts.",
        ["energy-shield-mk2-equipment"]="Inséré dans les combinaisons pour absorber beaucoup de dégâts.",
        ["solar-panel-equipment"]="Inséré dans les combinaisons pour alimenter d'autres équipements, mais inutiles la nuit.",
        ["fission-reactor-equipment"]="Inséré dans les combinaisons pour alimenter d'autres équipements.",
        ["night-vision-equipment"]="Inséré dans les combinaisons pour mieux voir la nuit.",
        ["belt-immunity-equipment"]="Inséré dans les combinaisons pour éviter d'être déplacés par les convoyeurs.",
        ["exoskeleton-equipment"]="Inséré dans les combinaisons pour augmenter la vitesse de déplacement. Vous pouvez équiper plusieurs exosquelettes à la fois.",
        ["personal-roboport-equipment"]="Inséré dans les combinaisons pour permettre aux robots de construction de travailler à partir de votre inventaire.",
        ["personal-roboport-mk2-equipment"]="Inséré dans les combinaisons pour permettre à de nombreux robots de construction de travailler à partir de votre inventaire.",
        ["physical-projectile-damage"]="Augmente les dégâts des projectiles physiques de défense contre les astéroïdes.",
        ["weapon-shooting-speed"]="Augmente la vitesse de tir de la plupart des projectiles de défense contre les astéroïdes.",
        ["laser-shooting-speed"]="Augmente la vitesse de tir des défenses laser contre les astéroïdes.",
        ["laser-weapons-damage"]="Augmente les dégâts des défenses laser contre les astéroïdes.",
        ["stronger-explosives"]="Augmente les dégâts des missiles de défense contre les astéroïdes.",
        ["railgun"]="Défense contre les astéroïdes fonctionnant à l'électricité et tirant des projectiles à haute vitesse.",
        ["railgun-shooting-speed"]="Grâce à l'amélioration des systèmes de refroidissement, la défense à haute vitesse contre les astéroïdes peut tirer plus souvent.",
        ["railgun-damage"]="Le fait de rendre les projectiles à haute vitesse plus denses et plus robustes permet d'augmenter les dégâts.",
        ["rocket-turret"]="Une défense à longue portée contre les astéroïdes qui tire des missiles.",
        ["captive-biter-spawner"]="Fertiliser les spores dans des gisements contrôlés et les placer n'importe où sur Nauvis.",
        ["captivity"]="Une bio-sonde injecte une dose de [item=bioflux] dans le gisement de spores, contrôlant ainsi la mutation. Avec des doses régulières de [item=bioflux], le gisement restera sous contrôle.",
        ["biter-egg-handling"]="Contrôler un gisement de spores et lui fournir des doses régulières de [item=bioflux] permet de récolter des échantillons de spores, qui pourraient peut-être être utilisés...",
        ["biolab"]="Il semble qu'il y ait un moyen de cultiver les spores pour en faire quelque chose...",
    },
    ["tips-and-tricks-item-description"] = {
    }
    -------------------------
}
