return {
    ---------------
    --qol_research.cfg
    ["technology-name"] = {
        ["qol-crafting-speed-1"]="Vitesse de fabrication de base",
        ["qol-crafting-speed-2"]="Vitesse de fabrication intermédiaire",
        ["qol-crafting-speed-3"]="Vitesse de fabrication avancée",
        ["qol-crafting-speed-4"]="Vitesse de fabrication experte",
        ["qol-crafting-speed-5"]="Vitesse de fabrication de folie",
        ["qol-crafting-speed-6"]="Vitesse de fabrication extrême",
        ["qol-crafting-speed-7"]="Vitesse de fabrication stupéfiante",
        ["qol-crafting-speed-8"]="Vitesse de fabrication exceptionnelle",
        ["qol-crafting-speed-9"]="Vitesse de fabrication divine",
        ["qol-crafting-speed-10"]="Vitesse de fabrication miraculeuse",
        ["qol-crafting-speed-11"]="Vitesse de fabrication d'une autre monde",
        ["qol-crafting-speed-12"]="La vraie vitesse de fabrication, la seule",
        ["qol-inventory-size-1"]="Taille de l'inventaire de base",
        ["qol-inventory-size-2"]="Taille de l'inventaire intermédiaire",
        ["qol-inventory-size-3"]="Taille de l'inventaire avancée",
        ["qol-inventory-size-4"]="Taille de l'inventaire experte",
        ["qol-inventory-size-5"]="Taille de l'inventaire de folie",
        ["qol-inventory-size-6"]="Taille de l'inventaire extrême",
        ["qol-inventory-size-7"]="Taille de l'inventaire stupéfiante",
        ["qol-inventory-size-8"]="Taille de l'inventaire exceptionnelle",
        ["qol-inventory-size-9"]="Taille de l'inventaire divine",
        ["qol-inventory-size-10"]="Taille de l'inventaire miraculeuse",
        ["qol-inventory-size-11"]="Taille de l'inventaire d'une autre monde",
        ["qol-inventory-size-12"]="La vraie taille de l'inventaire, la seule",
        ["qol-mining-speed-1"]="Vitesse de minage de base",
        ["qol-mining-speed-2"]="Vitesse de minage intermédiaire",
        ["qol-mining-speed-3"]="Vitesse de minage avancée",
        ["qol-mining-speed-4"]="Vitesse de minage experte",
        ["qol-mining-speed-5"]="Vitesse de minage de folie",
        ["qol-mining-speed-6"]="Vitesse de minage extrême",
        ["qol-mining-speed-7"]="Vitesse de minage stupéfiante",
        ["qol-mining-speed-8"]="Vitesse de minage exceptionnelle",
        ["qol-mining-speed-9"]="Vitesse de minage divine",
        ["qol-mining-speed-10"]="Vitesse de minage miraculeuse",
        ["qol-mining-speed-11"]="Vitesse de minage d'une autre monde",
        ["qol-mining-speed-12"]="La vraie vitesse de minage, la seule",
        ["qol-movement-speed-1"]="Vitesse de déplacement de base",
        ["qol-movement-speed-2"]="Vitesse de déplacement intermédiaire",
        ["qol-movement-speed-3"]="Vitesse de déplacement avancée",
        ["qol-movement-speed-4"]="Vitesse de déplacement experte",
        ["qol-movement-speed-5"]="Vitesse de déplacement de folie",
        ["qol-movement-speed-6"]="Vitesse de déplacement extrême",
        ["qol-movement-speed-7"]="Vitesse de déplacement stupéfiante",
        ["qol-movement-speed-8"]="Vitesse de déplacement exceptionnelle",
        ["qol-movement-speed-9"]="Vitesse de déplacement divine",
        ["qol-movement-speed-10"]="Vitesse de déplacement miraculeuse",
        ["qol-movement-speed-11"]="Vitesse de déplacement d'une autre monde",
        ["qol-movement-speed-12"]="La vraie vitesse de déplacement, la seule",
        ["qol-player-reach-1"]="Portée de base",
        ["qol-player-reach-2"]="Portée intermédiaire",
        ["qol-player-reach-3"]="Portée avancée",
        ["qol-player-reach-4"]="Portée experte",
        ["qol-player-reach-5"]="Portée de folie",
        ["qol-player-reach-6"]="Portée extrême",
        ["qol-player-reach-7"]="Portée stupéfiante",
        ["qol-player-reach-8"]="Portée exceptionnelle",
        ["qol-player-reach-9"]="Portée divine",
        ["qol-player-reach-10"]="Portée miraculeuse",
        ["qol-player-reach-11"]="Portée d'une autre monde",
        ["qol-player-reach-12"]="La vraie portée, la seule",
    },
    ["technology-description"] = {
    }
    -------------------------
}
