return {
    ---------------
    --RampantFixed.cfg
    ["damage-type-name"] = {
        ["rampant-longRangeImmunity"]="Immunité à longue portée",
        ["rampant-overdamageProtection"]="Protection contre les dégâts supplémentaires, dégâts maximums",
        ["healing"]="soins",
    },
    ["technology-name"] = {
        ["biterSupressor1-rampant"]="IA Rampant. Suppression de l'agressivité 1",
        ["biterSupressor2-rampant"]="IA Rampant. Suppression de l'agressivité 2",
        ["biterSupressor3-rampant"]="IA Rampant. Suppression de l'agressivité 3",
        ["demolisher-feeding-rampant"]="Alimentation des démolisseurs",
        ["biterEggs-rampant"]="Capture de ruches Rampant",
    },
    ["technology-description"] = {
        ["biterSupressor1-rampant"]="Outils de base pour réduire de manière significative la pression de l'IA sur les planètes dépourvues de joueurs",
        ["biterSupressor2-rampant"]="Outils avancés permettant de réduire considérablement la pression exercée par l'IA sur les planètes dépourvues de joueurs",
        ["biterSupressor3-rampant"]="Outils de haute technologie permettant de réduire considérablement la pression exercée par l'IA sur les planètes dépourvues de joueurs",
        ["demolisher-feeding-rampant"]="Solution si vous ne pouvez pas tuer les démolisseurs qui attaquent",
        ["biterEggs-rampant"]="Débloque des moyens de capturer des ruches de Rampant, d'obtenir des œufs et les transformer.",
    },
    ["entity-name"] = {
        ["fire-flame-shortlife-rampant"]="Feu",
        ["safe-fire-flame-rampant"]="Feu sûr",
        ["biters-safe-fire-rampant"]="Feu sûr",
        ["regenerationCrystal-rampantFixed"]="Cristal de régénération",
        ["lootStone_Combat5-rampantFixed"]="Grès",
        ["biterSupressor1-rampant"]="Suppresseur d'agression des Biters, Niv.1",
        ["biterSupressor2-rampant"]="Suppresseur d'agression des Biters, Niv.2",
        ["biterSupressor3-rampant"]="Suppresseur d'agression des Biters, Niv.3",
        ["demolisher-food-rocket-rampant"]="Missile démolisseur d'aliments",
        ["targetDummyPlasma-rampant"]="Cristal d'absorption instable",
        ["targetDummyFire-rampant"]="Cristal ignifuge instable",
        ["targetDummyPhysical-rampant"]="Cristal blindé instable",
        ["targetDummyLaser-rampant"]="Cristal de dispersion instable",
        ["plasmaDummySetter-rampant"]="Sertisseur de cristaux (absorption)",
        ["fireDummySetter-rampant"]="Sertisseur de cristaux (ignifuge) ",
        ["physicalDummySetter-rampant"]="Sertisseur de cristaux (blindé) ",
        ["laserDummySetter-rampant"]="Sertisseur de cristaux (dispersion) ",
        ["randomDummySetter-rampant"]="Sertisseur de cristaux ",
        ["crystal-v1-drain-rampant"]="Cristal draineur d'énergie",
        ["crystal-v2-drain-rampant"]="Cristal draineur d'énergie",
        ["crystal-v3-drain-rampant"]="Cristal draineur d'énergie",
        ["crystal-v4-drain-rampant"]="Cristal draineur d'énergie",
        ["crystal-v5-drain-rampant"]="Cristal draineur d'énergie",
        ["crystal-v6-drain-rampant"]="Cristal draineur d'énergie",
        ["crystal-v7-drain-rampant"]="Cristal draineur d'énergie",
        ["crystal-v8-drain-rampant"]="Cristal draineur d'énergie",
        ["crystal-v9-drain-rampant"]="Cristal draineur d'énergie",
        ["crystal-v10-drain-rampant"]="Cristal draineur d'énergie",
        ["crystal-drain-pole-rampant"]="Pylône de cristal",
        ["pylon-target-rampant"]="Pylône de cristal",
        ["acid-ball-acid-fire-rampant"]="Flaque d'acide",
        ["acid-ball-1-acid-fire-rampant"]="Flaque d'acide",
        ["acid-ball-2-acid-fire-rampant"]="Flaque d'acide",
        ["acid-ball-2-direction-acid-fire-rampant"]="Flaque d'acide",
        ["acid-ball-3-acid-fire-rampant"]="Flaque d'acide",
        ["acid-ball-3-direction-acid-fire-rampant"]="Flaque d'acide",
        ["acid-ball-4-acid-fire-rampant"]="Flaque d'acide",
        ["acid-ball-5-acid-fire-rampant"]="Flaque d'acide",
        ["poison-cloud-Dmg-Heal1-cloud-rampant"]="Nuage de poison guérisseur",
        ["poison-cloud-Dmg-Heal2-cloud-rampant"]="Nuage de poison guérisseur",
        ["poison-cloud-Dmg-Heal3-cloud-rampant"]="Nuage de poison guérisseur",
        ["poison-cloud-Dmg-Heal4-cloud-rampant"]="Nuage de poison guérisseur",
        ["poison-cloud-Dmg-Heal5-cloud-rampant"]="Nuage de poison guérisseur",
        ["poison-cloud-Dmg-Heal6-cloud-rampant"]="Nuage de poison guérisseur",
        ["poison-cloud-Dmg-Heal7-cloud-rampant"]="Nuage de poison guérisseur",
        ["poison-cloud-Dmg-Heal8-cloud-rampant"]="Nuage de poison guérisseur",
        ["poison-cloud-Dmg-Heal9-cloud-rampant"]="Nuage de poison guérisseur",
        ["poison-cloud-Dmg-Heal10-cloud-rampant"]="Nuage de poison guérisseur",
        ["spawner-proxy-1-rampant"]="Nid fictif",
        ["spawner-proxy-2-rampant"]="Nid fictif",
        ["spawner-proxy-3-rampant"]="Nid fictif",
    },
    ["entity-description"] = {
        ["regenerationCrystal-rampantFixed"]="[color=green]Peut être récupéré\nAccorde du soin aux joueurs amis s'il est activé[/color][color=red]\nPeut se briser lors de l'application d'un bonus[/color]",
        ["lootStone_Combat5-rampantFixed"]="Pierre de butin\nRécupérez ou détruisez-la",
    },
    ["item-name"] = {
        ["powerup-Combat5min-Capsule-rampantFixed"]="Renforcement : combat (5 min)",
        ["demolisher-food-rocket-rampant"]="Missile d'aliment pour démolisseur",
    },
    ["item-description"] = {
        ["demolisher-food-rocket-rampant"]="À lancer sur le démolisseur en cas d'attaque. Il ne reviendra pas avant au moins une heure. Les grands démolisseurs peuvent en manger davantage",
    }
    -------------------------
}
