return {
    ---------------
    --SchallTankPlatoon.cfg
    ["entity-name"] = {
        ["Schall-tank-L"]="Char d'assaut léger",
        ["Schall-tank-M"]="Char d'assaut moyen",
        ["Schall-tank-H"]="Char d'assaut lourd",
        ["Schall-tank-SH"]="Char d'assaut super-lourd",
        ["Schall-tank-F"]="Char d'assaut lance-flammes",
        ["Schall-ht-RA"]="Artillerie lance-roquettes",
        ["Schall-concrete-wall"]="Mur en béton",
        ["Schall-concrete-gate"]="Porte en béton",
        ["stone-wall"]="Mur en pierre",
        ["gate"]="Porte en pierre",
    },
    ["item-name"] = {
        ["Schall-tech-damage"]=" dégâts",
        ["Schall-tech-shooting-speed"]=" vitesse de tir",
        ["Schall-mod-damage"]=" dégâts",
        ["Schall-mod-shooting-speed"]=" vitesse de tir",
        ["Schall-tank-machine-gun-single"]="Mitrailleuse simple pour char d'assaut",
        ["tank-machine-gun"]="Mitrailleuse double pour char d'assaut",
        ["Schall-autocannon-shell-type"]="Obus pour canon automatique (20 mm)",
        ["Schall-tank-autocannon"]="Canon automatique pour char d'assaut (20 mm)",
        ["Schall-explosive-autocannon-shell"]="Obus explosif pour canon automatique (20 mm)",
        ["Schall-explosive-uranium-autocannon-shell"]="Obus explosif à l'uranium pour canon automatique (20 mm)",
        ["Schall-incendiary-autocannon-shell"]="Obus incendiaire pour canon automatique (20 mm)",
        ["Schall-cannon-shell-type"]="Obus pour canon (75mm)",
        ["tank-cannon"]="Canon pour char d'assaut (75 mm)",
        ["cannon-shell"]="Obus pour canon (75 mm)",
        ["uranium-cannon-shell"]="Obus à l'uranium pour canon (75 mm)",
        ["explosive-cannon-shell"]="Obus explosif pour canon (75 mm)",
        ["explosive-uranium-cannon-shell"]="Obus explosif à l'uranium pour canon (75 mm)",
        ["Schall-cannon-H1-shell-type"]="Obus pour canon (88mm)",
        ["Schall-tank-cannon-H1"]="Canon pour char d'assaut (88 mm)",
        ["Schall-cannon-H1-shell"]="Obus pour canon (88 mm)",
        ["Schall-uranium-cannon-H1-shell"]="Obus à l'uranium pour canon (88 mm)",
        ["Schall-explosive-cannon-H1-shell"]="Obus explosif pour canon (88 mm)",
        ["Schall-explosive-uranium-cannon-H1-shell"]="Obus explosif à l'uranium pour canon (88 mm)",
        ["Schall-cannon-H2-shell-type"]="Obus pour canon (128mm)",
        ["Schall-tank-cannon-H2"]="Canon pour char d'assaut (128 mm)",
        ["Schall-cannon-H2-shell"]="Obus pour canon (128 mm)",
        ["Schall-uranium-cannon-H2-shell"]="Obus à l'uranium pour canon (128 mm)",
        ["Schall-explosive-cannon-H2-shell"]="Obus explosif pour canon (128 mm)",
        ["Schall-explosive-uranium-cannon-H2-shell"]="Obus explosif à l'uranium pour canon (128 mm)",
        ["Schall-tactical-missile-launcher"]="Lanceur de missiles tactiques",
        ["Schall-multiple-rocket-launcher"]="Lance-roquettes multiples",
        ["Schall-explosive-rocket-pack"]="Pack de fusées explosives",
        ["Schall-incendiary-rocket"]="Fusée incendiaire",
        ["Schall-napalm-bomb"]="Bombe au napalm",
        ["Schall-poison-bomb"]="Bombe toxique",
        ["Schall-sniper-rifle"]="Fusil de précision",
    },
    ["entity-description"] = {
        ["Schall-tank-L"]="Grande mobilité et maniabilité.",
        ["Schall-tank-M"]="Équilibre entre mobilité, puissance de feu et blindage. Convient à la plupart des missions.",
        ["Schall-tank-H"]="Une puissance de feu et un blindage renforcés, au détriment d'une certaine mobilité et maniabilité.",
        ["Schall-tank-SH"]="Un blindage extrême au prix de la mobilité et de la maniabilité.",
        ["Schall-tank-F"]="Un lance-flammes comme armement principal.",
        ["Schall-ht-RA"]="Capable de lancer des roquettes de bombes à fragmentation.",
    },
    ["item-description"] = {
        ["Schall-tank-L"]="Grande mobilité et maniabilité.",
        ["Schall-tank-M"]="Équilibre entre mobilité, puissance de feu et blindage. Convient à la plupart des missions.",
        ["Schall-tank-H"]="Une puissance de feu et un blindage renforcés, au détriment d'une certaine mobilité et maniabilité.",
        ["Schall-tank-SH"]="Un blindage extrême au prix de la mobilité et de la maniabilité.",
        ["Schall-tank-F"]="Un lance-flammes comme armement principal.",
        ["Schall-ht-RA"]="Capable de lancer des roquettes de bombes à fragmentation.",
        ["Schall-explosive-rocket-pack"]="Le faisceau se sépare lorsqu'il est lancé depuis le véhicule.",
        ["Schall-fission-reactor-2-equipment"]="Fournit de l'énergie aux modules d'équipement.",
        ["Schall-fission-reactor-3-equipment"]="Fournit de l'énergie aux modules d'équipement.",
        ["fusion-reactor-2-equipment"]="Fournit l'énergie pour les unités d'équipement.",
        ["fusion-reactor-3-equipment"]="Fournit l'énergie pour les unités d'équipement.",
        ["Schall-vehicle-energy-shield-equipment"]="Fournit un bouclier d'énergie pour protéger le véhicule.",
        ["Schall-vehicle-energy-shield-mk2-equipment"]="Fournit un bouclier d'énergie pour protéger le véhicule.",
        ["Schall-vehicle-battery-equipment"]="Stocke l'énergie électrique pour les unités d'équipement des véhicules.",
        ["Schall-vehicle-battery-mk2-equipment"]="Stocke l'énergie électrique pour les unités d'équipement des véhicules.",
        ["Schall-vehicle-fuel-cell-2-equipment"]="Fournit l'énergie pour les unités d'équipement. Brûle du carburant chimique avec un rendement de 80%.",
        ["Schall-vehicle-fuel-cell-3-equipment"]="Fournit l'énergie pour les unités d'équipement. Brûle du carburant chimique avec un rendement de 90%.",
        ["Schall-vehicle-fuel-cell-4-equipment"]="Fournit l'énergie pour les unités d'équipement. Brûle du carburant chimique avec un rendement de 100%.",
        ["Schall-vehicle-nuclear-reactor-equipment"]="Fournit l'énergie pour les unités d'équipement. Brûle du carburant nucléaire avec un rendement de 50%.",
    },
    ["equipment-name"] = {
        ["Schall-fission-reactor-2-equipment"]="Réacteur de fission portable 2×2",
        ["Schall-fission-reactor-3-equipment"]="Réacteur de fission portable 3×3",
        ["Schall-fusion-reactor-2-equipment"]="Réacteur de fusion portable 2×2",
        ["Schall-fusion-reactor-3-equipment"]="Réacteur de fusion portable 3×3",
        ["Schall-vehicle-energy-shield-equipment"]="Bouclier d'énergie pour véhicules",
        ["Schall-vehicle-energy-shield-mk2-equipment"]="Bouclier d'énergie pour véhicules MK2",
        ["Schall-vehicle-battery-equipment"]="Batterie pour véhicule",
        ["Schall-vehicle-battery-mk2-equipment"]="Batterie pour véhicule MK2",
        ["Schall-vehicle-fuel-cell-2-equipment"]="Pile à combustible pour véhicules 2×2",
        ["Schall-vehicle-fuel-cell-3-equipment"]="Pile à combustible pour véhicules 3×3",
        ["Schall-vehicle-fuel-cell-4-equipment"]="Pile à combustible pour véhicules 4×4",
        ["Schall-vehicle-nuclear-reactor-equipment"]="Réacteur nucléaire pour véhicules",
        ["Schall-night-vision-mk1-equipment"]="Vision nocturne MK1",
        ["Schall-night-vision-mk2-equipment"]="Vision nocturne MK2",
    },
    ["ammo-category-name"] = {
    },
    ["technology-name"] = {
        ["Schall-tank"]="Tank",
        ["Schall-night-vision-equipment"]="Équipement de vision nocturne",
        ["Schall-concrete-wall"]="Mur en béton",
        ["Schall-firearms-ballistics"]="Balistique des armes à feu",
    },
    ["technology-description"] = {
        ["Schall-tank"]="La mobilité supplémentaire, la puissance de feu et le blindage combinés, permettent une meilleure survie dans ce monde hostile.",
        ["Schall-tank-F"]="Adaptation simple de la technologie du lance-flammes sur le châssis d'un char d'assaut de taille moyenne.",
        ["Schall-ht-RA"]="L'artillerie lance-roquettes est capable de lancer des roquettes de bombes à fragmentation.",
        ["Schall-sniper-rifle"]="Éliminer les ennemis à très longue distance.",
        ["Schall-repair-pack"]="Réparer les entités plus rapidement.",
        ["Schall-firearms-ballistics"]="Augmente les dégâts des balles.",
    }
    -------------------------
}
