return {
    ---------------
    --space-age(doublons).cfg
    ["achievement-description"] = {
        ["look-at-my-shiny-rare-armor"]="S'équiper d'une armure de puissance MK2 de qualité rare ou plus, ou d'une armure Mécha.",
        ["my-modules-are-legendary"]="Fabriquer un module de qualité 3 légendaire.",
        ["no-room-for-more"]="Remplissez chaque emplacement d'une armure Mécha légendaire avec des équipements légendaires.",
        ["todays-fish-is-trout-a-la-creme"]="Mangez un poisson légendaire.",
    },
    ["achievement-name"] = {
        ["my-modules-are-legendary"]="Mes modules sont légendaires",
    },
    ["ammo-category-name"] = {
        ["railgun"]="Canon électromagnétique",
    },
    ["entity-description"] = {
        ["big-mining-drill"]="Une foreuse plus grande et plus puissante avec une grande zone d'extraction. Peut extraire des minerais plus résistants.",
        ["capture-robot"]="Capture le [entity=biter-spawner] ciblé et le transforme en un [entity=captive-biter-spawner].",
        ["capture-robot-rocket"]="Capture le [entity=biter-spawner] ciblé et le transforme en un [entity=captive-biter-spawner].",
        ["offshore-pump"]="Extrait des fluides à partir d'étendues d'eau, de lave et de divers océans.",
        ["railgun-turret"]="Tourelle à canon électromagnétique à longue portée. Efficace contre les ennemis et les astéroïdes.",
        ["rocket-silo"]="Utilisé pour envoyer des objets et des joueurs sur des plateformes spatiales.",
        ["rocket-turret"]="",
    },
    ["entity-name"] = {
        ["captive-biter-spawner"]="Nid de Biters captif",
        ["capture-robot"]="Robot de capture",
        ["capture-robot-rocket"]="Missile de capture",
        ["gleba-spawner"]="Radeau d'œufs",
        ["gleba-spawner-corpse"]="Cadavre d'un nid de Gléba",
        ["gleba-spawner-corpse-small"]="Cadavre d'un petit nid de Gléba",
        ["gleba-spawner-small"]="Petit radeau d'œufs",
        ["railgun-turret"]="Tourelle à canon électromagnétique",
        ["rocket-turret"]="Tourelle lance-missile",
        ["scrap"]="Débris",
        ["stack-inserter"]="Bras robotisé empileur",
        ["turbo-loader"]="Chargeur turbo",
        ["turbo-splitter"]="Répartiteur turbo",
        ["turbo-transport-belt"]="Convoyeur turbo",
        ["turbo-underground-belt"]="Convoyeur souterrain turbo",
    },
    ["equipment-name"] = {
        ["fusion-reactor-equipment"]="Réacteur de fusion portatif",
    },
    ["item-description"] = {
        ["biolab"]="",
        ["capture-robot-rocket"]="Capture le [entity=biter-spawner] ciblé et le transforme en un [entity=captive-biter-spawner].",
        ["fusion-reactor-equipment"]="Fournit de l'énergie aux équipements.",
        ["scrap"]="",
        ["space-science-pack"]="Utilisés dans les laboratoires pour faire des recherches. Obtenus en transformant des astéroïdes dans l'espace.",
    },
    ["item-name"] = {
        ["agricultural-science-pack"]="Pack de science agricole",
        ["biter-egg"]="Œuf de Biters",
        ["captive-biter-spawner"]="Nid de Biters captif",
        ["capture-robot-rocket"]="Missile de capture",
        ["carbon-fiber"]="Fibre de carbone",
        ["cryogenic-science-pack"]="Pack de science cryogénique",
        ["electromagnetic-science-pack"]="Pack de science électromagnétique",
        ["lithium"]="Lithium",
        ["mech-armor"]="Armure Mécha",
        ["metallurgic-science-pack"]="Pack de science métallurgique",
        ["nutrients"]="Nutriments",
        ["pentapod-egg"]="Oeuf de pentapode",
        ["promethium-science-pack"]="Pack de science de prométhium",
        ["railgun"]="Canon électromagnétique",
        ["railgun-ammo"]="Munition pour canon électromagnétique",
        ["scrap"]="Débris",
        ["tungsten-carbide"]="Carbure de tungstène",
        ["tungsten-ore"]="Minerai de tungstène",
        ["turbo-splitter"]="Répartiteur turbo",
        ["turbo-transport-belt"]="Convoyeur turbo",
        ["turbo-underground-belt"]="Convoyeur souterrain turbo",
    },
    ["recipe-name"] = {
        ["nutrients-from-bioflux"]="Nutriments à partir de bioflux",
        ["nutrients-from-biter-egg"]="Nutriments provenant d'œufs de Biters",
        ["nutrients-from-fish"]="Nutriments provenant de poissons",
        ["nutrients-from-spoilage"]="Nutriments à partir de pourritures",
        ["nutrients-from-yumako-mash"]="Nutriments à partir de purée de Yumako",
        ["scrap-recycling"]="Recyclage des débris",
    },
    ["technology-description"] = {
        ["belt-capacity"]="Augmenter la hauteur des piles d'objets sur les convoyeurs.",
        ["biolab"]="Il semble qu'il existe un moyen de cultiver les œufs pour en faire quelque chose...",
        ["biter-egg-handling"]="Capturer un nid de Biters et lui fournir des doses régulières de [item=bioflux] permet de récolter des œufs de Biters, peut-être pourraient-ils même être utilisés...",
        ["captive-biter-spawner"]="Faire éclore des œufs pour en faire des nids captifs et les placer n'importe où sur Nauvis.",
        ["carbon-fiber"]="Certaines plantes produisent naturellement des nanotubes de carbone, qui peuvent être filés en fibres et tissés pour former des tissus extrêmement résistants.",
        ["foundry"]="Permet une fonte plus élaborée et d'autres avancées métallurgiques.",
        ["fusion-reactor-equipment"]="À placer dans une armure pour fournir de l'énergie aux autres équipements.",
        ["laser-weapons-damage"]="Augmente les dégâts des rayons laser.",
        ["quantum-processor"]="Processeur qui exploite plusieurs phénomènes quantiques pour diverses applications.",
        ["railgun"]="Un croisement électrique entre un canon et un fusil de précision.",
        ["railgun-damage"]="Le fait de rendre les projectiles pour canon électromagnétique plus denses et plus robustes permet d'augmenter les dégâts.",
        ["railgun-shooting-speed"]="Des systèmes de refroidissement améliorés permettent au canon électromagnétique de tirer plus souvent.",
        ["rocket-silo"]="Utilisé pour envoyer des objets et des joueurs sur des plateformes spatiales.",
        ["rocket-turret"]="Une tourelle à longue portée qui tire des missiles.",
        ["tree-seeding"]="Collecter des graines d'arbres et plantez-les sur de l'herbe ou de la terre.",
    },
    ["technology-name"] = {
        ["agricultural-science-pack"]="Pack de science agricole",
        ["biter-egg-handling"]="Manipulation des œufs de Biters",
        ["captive-biter-spawner"]="Nid de Biters captif",
        ["captivity"]="Captivité",
        ["carbon-fiber"]="Fibre de carbone",
        ["cryogenic-science-pack"]="Pack de science cryogénique",
        ["electromagnetic-science-pack"]="Pack de science électromagnétique",
        ["fusion-reactor-equipment"]="Réacteur de fusion portatif",
        ["laser-weapons-damage"]="Dégâts des armes laser",
        ["metallurgic-science-pack"]="Pack de science métallurgique",
        ["promethium-science-pack"]="Pack de science de prométhium",
        ["quantum-processor"]="Processeur quantique",
        ["railgun"]="Canon électromagnétique",
        ["railgun-damage"]="Dégâts des canons électromagnétiques",
        ["railgun-shooting-speed"]="Vitesse de tir des canons électromagnétiques",
        ["rocket-turret"]="Tourelle lance-missile",
        ["transport-belt-capacity"]="Capacité des convoyeurs",
        ["tree-seeding"]="Semis d'arbres",
        ["turbo-transport-belt"]="Convoyeur turbo",
    },
    ["tips-and-tricks-item-description"] = {
        ["spoilables-research"]="Le [item=agricultural-science-pack] perd de sa valeur au fur et à mesure qu'il s'abîme.",
        ["spoilables-result"]="L'évolution du pourrissement d'un ingrédient détermine aussi l'évolution du pourrissement du produit.",
    }
    -------------------------
}
