return {
    ---------------
    --team_competition.cfg
    ["recipe-name"] = {
        ["tc_alt_rail"]="Rail alternatif",
    },
    ["item-name"] = {
        ["tc_id_card-1"]="Carte de sécurité de niveau 1",
        ["tc_id_card-2"]="Carte de sécurité de niveau 2",
        ["tc_id_card-3"]="Carte de sécurité de niveau 3",
        ["mf-diggy-hole"]="Tunnel pour biters",
        ["tc_market"]="Marché",
        ["tc_portable_loader_in"]="Entrée du chargeur de récolte",
        ["tc_portable_loader_out"]="Sortie du chargeur de récolte",
        ["tc_portable_loader_coal_in"]="Entrée charbon du chargeur de récolte",
        ["crashed-generator"]="Générateur portable",
        ["tc_deep_mineral_extractor"]="Extracteur de minéraux profonds",
        ["uvaz-plate"]="Plaque dimensionnelle",
        ["ship_expanding_tile"]="Pièce de vaisseau en expansion",
        ["uvaz_refined_concrete"]="Béton dimensionnel",
        ["msi-ore-uvaz"]="Minerai dimensionnel",
        ["msi-uvaz-module"]="Module dimensionnel",
    },
    ["item-description"] = {
        ["ship_expanding_tile"]="Utilisez-le pour agrandir l'espace intérieur du vaisseau spatial.",
    },
    ["entity-name"] = {
        ["fake_human_machine_gunner"]="Homme avec une mitrailleuse",
        ["fake_human_melee"]="Homme avec une pioche",
        ["fake_human_pistol_gunner"]="Homme avec un pistolet",
        ["fake_human_sniper"]="Homme avec fusil de précision",
        ["fake_human_laser"]="Homme avec un fusil laser",
        ["fake_human_electric"]="Homme avec un fusil électrique",
        ["fake_human_erocket"]="Homme avec un lance-roquettes",
        ["fake_human_rocket"]="Homme avec un lance-roquettes",
        ["fake_human_grenade"]="Homme avec une grenade",
        ["fake_human_cluster_grenade"]="Homme avec une grenade à fragmentation",
        ["fake_human_nuke_rocket"]="Homme avec une bombe atomique",
        ["fake_human_boss_melee"]="Boss avec une pioche",
        ["fake_human_boss_machine_gunner"]="Boss avec une mitrailleuse",
        ["fake_human_boss_pistol_gunner"]="Boss avec un pistolet",
        ["fake_human_boss_sniper"]="Boss avec fusil de précision",
        ["fake_human_boss_laser"]="Boss avec un fusil laser",
        ["fake_human_boss_electric"]="Boss avec un fusil électrique",
        ["fake_human_boss_erocket"]="Boss avec un lance-roquettes",
        ["fake_human_boss_rocket"]="Boss avec un lance-roquettes",
        ["fake_human_boss_grenade"]="Boss avec une grenade",
        ["fake_human_boss_cluster_grenade"]="Boss avec une grenade à fragmentation",
        ["fake_human_boss_nuke_rocket"]="Boss avec une bombe atomique",
        ["tc_market"]="Marché",
        ["tc_leak_radar"]="Sabotage de l'énergie",
        ["tc_terminal"]="Terminal",
        ["tc_broken_reactor"]="Réacteur endommagé",
        ["tc_rocket_drop_pod"]="Fusée",
        ["tc_alien_egg_chest"]="Œuf d'Alien",
        ["maf-big-spawner"]="Nid géant",
        ["tc_export_chest"]="Coffre d'exportation",
        ["tc_import_chest"]="Coffre d'importation",
        ["tc_seller_chest"]="Coffre de vente",
        ["tc_fortress_portal"]="Portail",
        ["tc_fortress_tank"]="Chars d'assaut de forteresse",
        ["tc_fortress_spider"]="Spidertron de forteresse",
        ["tc_portable_loader_in"]="Entrée du chargeur de récolte",
        ["tc_portable_loader_coal_in"]="Entrée charbon du chargeur de récolte",
        ["tc_portable_loader_out"]="Sortie du chargeur de récolte",
        ["boiler"]="Chaudière à réservoir",
        ["tc_mule_1"]="La Mule",
        ["tc_big_chest"]="Grand coffre",
        ["tc_capsule_explosion"]="Effet spécial",
        ["msi-ore-solaz"]="Solaz",
        ["msi-ore-bludaz"]="Bludaz",
        ["msi-ore-uvaz"]="Minerai dimensionnel",
        ["mf-hole-spawner"]="Tunnel pour biters",
        ["mf-diggy-hole"]="Tunnel pour biters",
        ["maf-boss-biter"]="Boss mordeur",
        ["maf-boss-spitter"]="Boss cracheur",
        ["tc_factory_chest"]="Usine de production infinie",
        ["tc_recharge_factory"]="Usine de production infinie",
        ["tc_fake_human_gun-turret"]="Tourelle mitrailleuse",
        ["tc_fake_human_laser-turret"]="Tourelle laser",
        ["tc_portal_gate"]="Porte",
    },
    ["entity-description"] = {
        ["tc_alien_egg_chest"]="Cet œuf consomme des packs de science toutes les minutes pour faire apparaître des aliens à l'emplacement du trou. Remarque : vous pouvez déplacer le trou à un autre endroit.",
        ["tc_factory_chest"]="Une fois que cette usine fonctionnera, elle produira des objets gratuits.",
        ["tc_recharge_factory"]="Pour rendre cette usine opérationnelle, vous devez la charger à pleine puissance. Une fois en fonctionnement, elle produit des objets gratuits.",
        ["tc_seller_chest"]="Tous les objets insérés qui ont une valeur marchande seront vendus pour une partie de leur prix, selon le scénario.",
    },
    ["technology-name"] = {
        ["tc_base_size_tech"]="Taille de la base principale",
        ["tc_tank_internal_size_tech"]="Taille intérieure de la forteresse",
        ["tc_train_internal_size_tech"]="Taille intérieure du train",
        ["tc_harvest_loader_tech"]="Chargeurs de récolte",
        ["tc_deep_mineral_extractor_tech"]="Extracteur de minéraux profonds",
        ["tc_compilatron_tech"]="Une meilleure Mule",
        ["tc_mining_speed_tech"]="Amélioration de la vitesse d'extraction",
        ["tc_market_upgrade_tech"]="Mise à niveau du marché",
    },
    ["technology-description"] = {
        ["tc_base_size_tech"]="Augmente la taille de la base principale",
        ["tc_tank_internal_size_tech"]="Augmente la taille intérieure de la forteresse",
        ["tc_train_internal_size_tech"]="Augmente la taille intérieure du train et le nombre de wagons que vous pouvez ajouter à votre train.",
        ["tc_harvest_loader_tech"]="Augmente la limite des chargeurs de récolte que vous pouvez utiliser simultanément",
        ["tc_deep_mineral_extractor_tech"]="Chaque niveau augmente l'efficacité de votre extracteur de minerais profonds et la capacité de votre navire.",
        ["tc_compilatron_tech"]="Chaque niveau augmente la santé, les dégâts et la résistance",
        ["tc_market_upgrade_tech"]="Chaque niveau augmente le nombre d'offres de marché et la probabilité de la qualité",
    },
    ["controls"] = {
        ["tc-special-key"]="Touche spéciale du mod (Entrer dans l'usine mobile / appeler La Mule)",
    },
    ["shortcut-name"] = {
        ["tc-toogle-menu"]="Afficher le menu (Team Competition)",
    }
    -------------------------
}
