return {
    ---------------
    --vtk-deep-core-mining.cfg
    ["entity-name"] = {
        ["  iron-ore-patch"]="Gisement de minerai de fer",
        ["  copper-ore-patch"]="Gisement de minerai de cuivre",
        ["  coal-patch"]="Gisement de charbon",
        ["  stone-patch"]="Gisement de pierre",
        ["  uranium-ore-patch"]="Gisement de minerais d'uranium",
        ["  tungsten-ore-patch"]="Gisement de minerais de tungstène",
        ["  calcite-patch"]="Gisement de calcite",
        ["  scrap-patch"]="Gisement de débrits",
        ["  vtk-deepcore-mining-crack"]="Fissures profondes",
        ["  vtk-deepcore-mining-moho"]="Foreuse minière Moho",
        ["  vtk-deepcore-mining-drill"]="Foreuse minière profonde",
        ["  vtk-deepcore-mining-drill-advanced"]="Foreuse minière profonde avancée",
        ["  vtk-deepcore-mining-drill-advanced-energy-companion"]="Interface énergétique pour les forages miniers profonds avancés",
        ["  vtk-deepcore-mining-drone"]="Drone d'extraction en profondeur",
    },
    ["technology-name"] = {
        ["  vtk-deepcore"]="Extraction en profondeur",
        ["  vtk-deepcore-mining"]="Foreuse minière profonde",
        ["  vtk-deepcore-mining-advanced"]="Foreuse minière profonde avancée",
    },
    ["technology-description"] = {
        ["  vtk-deepcore-mining-advanced"]="Technologie avancée pour pour une exploitation encore plus poussée des ressources provenant des profondeurs de la planète lorsque tout le minerai de surface ne suffit pas à alimenter la base.",
    },
    ["item-name"] = {
        ["  vtk-deepcore-mining-moho"]="Foreuse minière Moho",
        ["  vtk-deepcore-mining-drill"]="Foreuse minière profonde",
        ["  vtk-deepcore-mining-drill-advanced"]="Foreuse minière profonde avancée",
        ["  vtk-deepcore-mining-drone"]="Drone d'extraction en profondeur",
        ["  vtk-deepcore-mining-planner"]="Planificateur pour l'exploitation minière en profondeur",
        ["  vtk-deepcore-mining-ore-chunk"]="Bloc de minerai des profindeurs",
        ["  vtk-deepcore-mining-iron-ore-chunk"]="Bloc de minerai de fer des profondeurs",
        ["  vtk-deepcore-mining-copper-ore-chunk"]="Bloc de minerai de cuivre des profondeurs",
        ["  vtk-deepcore-mining-coal-chunk"]="Bloc de charbon des profondeurs",
        ["  vtk-deepcore-mining-stone-chunk"]="Bloc de pierre des profondeurs",
        ["  vtk-deepcore-mining-uranium-ore-chunk"]="Bloc de minerai d'uranium des profondeurs",
        ["  vtk-deepcore-mining-tungsten-ore-chunk"]="Bloc de minerai de tungstène des profondeurs",
        ["  vtk-deepcore-mining-calcite-chunk"]="Bloc de calcite des profondeurs",
        ["  vtk-deepcore-mining-scrap-chunk"]="Bloc de débrits des profondeurs",
    },
    ["item-description"] = {
        ["  vtk-deepcore-mining-drone"]="Composante des technologies d'exploitation minière en profondeur et consommée pour extraire le minerai des profondeurs.",
        ["  vtk-deepcore-mining-ore-chunk"]="Nécessite un raffinage intensif dans une usine chimique pour en extraire des blocs de minerai encore plus raffinables.",
        ["  vtk-deepcore-mining-iron-ore-chunk"]="Nécessite un raffinage dans une usine chimique pour obtenir du minerai de fer utilisable.",
        ["  vtk-deepcore-mining-copper-ore-chunk"]="Nécessite un raffinage dans une usine chimique pour obtenir du minerai de cuivre utilisable.",
        ["  vtk-deepcore-mining-coal-chunk"]="Nécessite un raffinage dans une usine chimique pour obtenir du charbon utilisable.",
        ["  vtk-deepcore-mining-stone-chunk"]="Nécessite un raffinage dans une usine chimique pour obtenir de la pierre utilisable.",
        ["  vtk-deepcore-mining-uranium-ore-chunk"]="Nécessite un raffinage dans une usine chimique pour obtenir du minerai d'uranium utilisable.",
        ["  vtk-deepcore-mining-tungsten-ore-chunk"]="Nécessite un raffinage dans une usine chimique pour obtenir du minerai de tungstène utilisable.",
        ["  vtk-deepcore-mining-calcite-chunk"]="Nécessite un raffinage dans une usine chimique pour obtenir du calcite utilisable.",
        ["  vtk-deepcore-mining-scrap-chunk"]="Nécessite un raffinage dans une usine chimique pour obtenir de débrits utilisable.",
    },
    ["recipe-name"] = {
        ["  vtk-deepcore-mining-ore-chunk-refining"]="Processus de raffinage et de triage des blocs de minerai provenant de gisements profonds",
        ["  vtk-deepcore-mining-ore-chunk-refining-no-uranium"]="Procédé de raffinage et de triage de morceaux de minerai des profondeurs ne nécessitant pas d'uranium",
        ["  vtk-deepcore-mining-ore-chunk-refining-iron-ore-focus"]="Processus de raffinage et de triage des blocs de minerai de fer provenant de gisements profonds, source de gaspillage, mais qui privilégie le rendement des blocs de minerai de fer",
        ["  vtk-deepcore-mining-ore-chunk-refining-copper-ore-focus"]="Processus de raffinage et de triage des blocs de minerai de cuivre provenant de gisements profonds, source de gaspillage, mais qui privilégie le rendement des blocs de minerai de cuivre",
        ["  vtk-deepcore-mining-ore-chunk-refining-coal-focus"]="Processus de raffinage et de triage des blocs de charbon provenant de gisements profonds, source de gaspillage, mais qui privilégie le rendement des blocs de charbon",
        ["  vtk-deepcore-mining-ore-chunk-refining-stone-focus"]="Processus de raffinage et de triage des blocs de pierre provenant de gisements profonds, source de gaspillage, mais qui privilégie le rendement des blocs de pierre",
        ["  vtk-deepcore-mining-ore-chunk-refining-uranium-ore-focus"]="Processus de raffinage et de triage des blocs de minerai d'uranium provenant de gisements profonds, source de gaspillage, mais qui privilégie le rendement des blocs d'uranium",
        ["  vtk-deepcore-mining-iron-ore-chunk-refining"]="Processus de raffinage des blocs de minerai de fer des profondeurs ",
        ["  vtk-deepcore-mining-copper-ore-chunk-refining"]="Processus de raffinage des blocs de minerai de cuivre des profondeurs ",
        ["  vtk-deepcore-mining-coal-chunk-refining"]="Processus de raffinage des blocs de charbon des profondeurs ",
        ["  vtk-deepcore-mining-stone-chunk-refining"]="Processus de raffinage des blocs de pierre des profondeurs ",
        ["  vtk-deepcore-mining-uranium-ore-chunk-refining"]="Processus de raffinage des blocs de minerai d'uranium des profondeurs ",
        ["  vtk-deepcore-mining-tungsten-ore-chunk-refining"]="Processus de raffinage des blocs de minerai de tungstène des profondeurs ",
        ["  vtk-deepcore-mining-calcite-chunk-refining"]="Processus de raffinage des blocs de calcite des profondeurs ",
        ["  vtk-deepcore-mining-scrap-chunk-refining"]="Processus de raffinage des blocs de débrits des profondeurs ",
    },
    ["recipe-description"] = {
        ["  vtk-deepcore-mining-ore-chunk-refining"]="Le processus de raffinage à l'acide sulfurique des blocs de minerai des profondeurs en d'autres blocs de minerai raffinables à l'intérieur d'une usine chimique.",
        ["  vtk-deepcore-mining-iron-ore-chunk-refining"]="Le processus de raffinage à l'acide sulfurique du minerai de fer des profondeurs permet d'obtenir un minerai de fer prêt à la production dans une usine chimique.",
        ["  vtk-deepcore-mining-copper-ore-chunk-refining"]="Le processus de raffinage à l'acide sulfurique du minerai de cuivre des profondeurs permet d'obtenir un minerai de cuivre prêt à la production dans une usine chimique.",
        ["  vtk-deepcore-mining-coal-chunk-refining"]="Le processus de raffinage à l'acide sulfurique du charbon des profondeurs permet d'obtenir un charbon prêt à la production dans une usine chimique.",
        ["  vtk-deepcore-mining-stone-chunk-refining"]="Le processus de raffinage à l'acide sulfurique de la pierre des profondeurs permet d'obtenir de la pierre prête à la production dans une usine chimique.",
        ["  vtk-deepcore-mining-uranium-ore-chunk-refining"]="Le processus de raffinage à l'acide sulfurique du minerai d'uranium des profondeurs permet d'obtenir un minerai d'uranium prêt à la production dans une usine chimique.",
        ["  vtk-deepcore-mining-tungsten-ore-chunk-refining"]="Le processus de raffinage à l'acide sulfurique du minerai de tungstène des profondeurs permet d'obtenir un minerai de tungstène prêt à la production dans une usine chimique.",
        ["  vtk-deepcore-mining-calcite-chunk-refining"]="Le processus de raffinage à l'acide sulfurique du calcite des profondeurs permet d'obtenir du calcite prêt à la production dans une usine chimique.",
        ["  vtk-deepcore-mining-scrap-chunk-refining"]="Le processus de raffinage à l'acide sulfurique des débrits des profondeurs permet d'obtenir des débrits prêts à la production dans une usine chimique.",
    },
    ["fuel-category-name"] = {
        ["  vtk-deepcore-mining-drone"]="Robot d'extraction de gisements profonds",
    }
    -------------------------
}
